const quizData = [
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "provide", meaning: "공급하다, 준비하다" },
  { word: "develop", meaning: "개발하다, 발전하다" },
  { word: "service", meaning: "서비스, 봉사" },
  { word: "inform", meaning: "알리다, 통지하다" },
  { word: "relationship", meaning: "관계" },
  { word: "improve", meaning: "향상시키다" },
  { word: "individual", meaning: "개인, 개인적인" },
  { word: "require", meaning: "요구하다" },
  { word: "advise", meaning: "조언하다, 충고하다" },
  { word: "social", meaning: "사회의, 사교적인" },
  { word: "amount", meaning: "총액, 총계, 양" },
  { word: "behave", meaning: "행동하다" },
  { word: "employ", meaning: "고용하다" },
  { word: "attitude", meaning: "태도, 입장" },
  { word: "research", meaning: "연구하다, 조사하다" },
  { word: "audience", meaning: "청중" },
  { word: "volunteer", meaning: "자원봉사자, 자원하다" },
  { word: "influence", meaning: "영향을 끼치다" },
  { word: "terrible", meaning: "끔찍한, 무서운" },
  { word: "opportunity", meaning: "기회" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "hesitate", meaning: "주저하다, 망설이다" },
  { word: "location", meaning: "위치" },
  { word: "restrict", meaning: "제한하다" },
  { word: "organism", meaning: "유기체, 생명체" },
  { word: "resolve", meaning: "해결하다, 결심하다" },
  { word: "offer", meaning: "제공하다, 제안하다" },
  { word: "distribute", meaning: "분배하다, 분포시키다" },
  { word: "rainforest", meaning: "열대우림" },
  { word: "circumstance", meaning: "환경, 상황" },
  { word: "interpret", meaning: "해석하다" },
  { word: "suitable", meaning: "적합한" },
  { word: "curve", meaning: "곡선, 구부리다" },
  { word: "annoy", meaning: "짜증나게 하다" },
  { word: "frighten", meaning: "겁먹게 하다" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "refuse", meaning: "거절하다" },
  { word: "adventure", meaning: "모험" },
  { word: "entrance", meaning: "입구, 입학" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "recite", meaning: "암송하다" },
  { word: "gather", meaning: "모으다" },
  { word: "cabin", meaning: "오두막, 객실" },
  { word: "gear", meaning: "장비, 기어" },
  { word: "ray", meaning: "광선" },
  { word: "release", meaning: "석방하다, 발표하다" },
  { word: "rank", meaning: "등급, 순위" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "alternative", meaning: "대안, 대안의" },
  { word: "retire", meaning: "은퇴하다" },
  { word: "appeal", meaning: "호소하다, 항의하다" },
  { word: "identical", meaning: "동일한" },
  { word: "investment", meaning: "투자" },
  { word: "autograph", meaning: "서명, 서명하다" },
  { word: "slave", meaning: "노예" },
  { word: "harm", meaning: "해, 해치다" },
  { word: "authority", meaning: "권위, 당국" },
  { word: "innocence", meaning: "결백, 순진" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "abolish", meaning: "폐지하다" },
  { word: "assure", meaning: "보증하다, 확실하게 하다" },
  { word: "form", meaning: "형태, 종류 / 형성하다" },
  { word: "gender", meaning: "성별" },
  { word: "innovation", meaning: "혁신" },
  { word: "opponent", meaning: "상대, 반대자" },
  { word: "present", meaning: "현재의, 나타나다" },
  { word: "fertile", meaning: "비옥한" },
  { word: "emperor", meaning: "황제" },
  { word: "dwell", meaning: "살다" },
  { word: "chore", meaning: "허드렛일" },
  { word: "rehearsal", meaning: "예행연습" },
  { word: "fossil", meaning: "화석" },
  { word: "glitter", meaning: "반짝이다" },
  { word: "carve", meaning: "조각하다" },
  { word: "decay", meaning: "부패하다" },
  { word: "protein", meaning: "단백질" },
  { word: "backward", meaning: "뒤쪽으로" },
  { word: "translate", meaning: "번역하다" },
  { word: "refresh", meaning: "상쾌하게 하다" },
  { word: "tissue", meaning: "조직, 화장지" },
  { word: "lord", meaning: "군주" },
  { word: "substitute", meaning: "대체하다" },
  { word: "scan", meaning: "정밀 검사하다" },
  { word: "pottery", meaning: "도자기" },
  { word: "layer", meaning: "층" },
  { word: "heritage", meaning: "유산" },
  { word: "estimate", meaning: "견적, 평가하다" },
  { word: "adventure", meaning: "모험" },
  { word: "persuade", meaning: "설득하다" },
  { word: "perceive", meaning: "인지하다" },
  { word: "symphony", meaning: "교향곡" },
  { word: "envy", meaning: "부러움" },
  { word: "corporate", meaning: "법인의" },
  { word: "subscribe", meaning: "구독하다" },
  { word: "enhance", meaning: "향상시키다" },
  { word: "imprint", meaning: "찍다, 각인시키다" },
  { word: "prefer", meaning: "선호하다" },
  { word: "ban", meaning: "금지하다" },
  { word: "despair", meaning: "절망하다" },
  { word: "alert", meaning: "경계하는" },
  { word: "famine", meaning: "기근" },
  { word: "pill", meaning: "알약" },
  { word: "immune", meaning: "면역의" },
  { word: "raw", meaning: "날것의" },
  { word: "cope", meaning: "대처하다" },
  { word: "bond", meaning: "유대" },
  { word: "procedure", meaning: "절차" },
  { word: "therapy", meaning: "치료" },
  { word: "outcome", meaning: "결과" },
  { word: "funeral", meaning: "장례식" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "diameter", meaning: "지름, 직경" },
  { word: "anecdote", meaning: "일화, 비화" },
  { word: "propriety", meaning: "적절성, 예의 바름" },
  { word: "blame", meaning: "비난하다, ~의 탓으로 돌리다" },
  { word: "earn", meaning: "얻다, 벌다" },
  { word: "pledge", meaning: "약속, 맹세, 약속하다, 맹세하다" },
  { word: "geology", meaning: "지질학" },
  { word: "detect", meaning: "발견하다, 감지하다" },
  { word: "temperate", meaning: "온화한, 절제하는" },
  { word: "soar", meaning: "높이 치솟다" },
  { word: "mock", meaning: "조롱하다, 가짜의" },
  { word: "exhibit", meaning: "전시하다, 보여주다, 전시, 전시품" },
  { word: "symptom", meaning: "증상" },
  { word: "invent", meaning: "발명하다" },
  { word: "awkward", meaning: "어색한, 서투른" },
  { word: "grind", meaning: "갈다, 빻다" },
  { word: "expose", meaning: "드러내다, 폭로하다, 노출시키다" },
  { word: "closet", meaning: "벽장" },
  { word: "damp", meaning: "축축한, 습기" },
  { word: "script", meaning: "손으로 쓰기, 대본" },
  { word: "possibility", meaning: "가능성" },
  { word: "discuss", meaning: "토론하다" },
  { word: "sibling", meaning: "형제자매" },
  { word: "lay", meaning: "놓다, 낳다" },
  { word: "flourish", meaning: "번영하다, 번창하다" },
  { word: "discharge", meaning: "배출, 방전, 배출하다, 내보내다" },
  { word: "undertake", meaning: "수행하다, 떠맡다" },
  { word: "linguistic", meaning: "언어의, 언어학의" },
  { word: "remedy", meaning: "치료, 치료하다" },
  { word: "feed", meaning: "먹이다, 부양하다" },
  { word: "remind", meaning: "상기시키다" },
  { word: "pillar", meaning: "기둥, 핵심" },
  { word: "explode", meaning: "폭발하다" },
  { word: "illusion", meaning: "환상" },
  { word: "submit", meaning: "제출하다, 복종하다" },
  { word: "divine", meaning: "신의, 신성한" },
  { word: "corrupt", meaning: "부패한, 타락시키다" },
  { word: "revenue", meaning: "수입, 수익" },
  { word: "swamp", meaning: "늪, 습지, 압도하다" },
  { word: "abnormal", meaning: "비정상적인" },
  { word: "revive", meaning: "소생시키다" },
  { word: "consistent", meaning: "일관된" },
  { word: "motion", meaning: "움직임, 운동" },
  { word: "virtue", meaning: "미덕" },
  { word: "deadline", meaning: "마감기한" },
  { word: "equator", meaning: "적도" },
  { word: "cognitive", meaning: "인지의" },
  { word: "hinder", meaning: "방해하다" },
  { word: "humble", meaning: "겸손한" },
  { word: "bounce", meaning: "튀다, 튀어오르다" },
  { word: "imprison", meaning: "투옥하다" },
  { word: "enlist", meaning: "모집하다, 도움을 얻다" },
  { word: "hygiene", meaning: "위생" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "recipe", meaning: "조리법" },
  { word: "deceive", meaning: "속이다" },
  { word: "sweep", meaning: "청소하다" },
  { word: "profile", meaning: "옆모습, 인물 소개" },
  { word: "enterprise", meaning: "기업, 사업" },
  { word: "successive", meaning: "연속되는, 상속의" },
  { word: "paradox", meaning: "역설" },
  { word: "surpass", meaning: "능가하다" },
  { word: "magnitude", meaning: "크기, 규모" },
  { word: "aesthetics", meaning: "미학" },
  { word: "earnest", meaning: "진지한" },
  { word: "tremble", meaning: "떨다" },
  { word: "surrender", meaning: "항복하다, 포기하다" },
  { word: "philosophy", meaning: "철학" },
  { word: "deplete", meaning: "고갈시키다" },
  { word: "admire", meaning: "감탄하다" },
  { word: "summon", meaning: "소환하다" },
  { word: "afford", meaning: "여유가 있다" },
  { word: "blunt", meaning: "무딘, 퉁명스러운" },
  { word: "tense", meaning: "긴장한" },
  { word: "stance", meaning: "입장, 태도" },
  { word: "collaborate", meaning: "협력하다" },
  { word: "division", meaning: "분할, 나누기" },
  { word: "ballot", meaning: "투표, 투표하다" },
  { word: "acquaintance", meaning: "지인, 아는 사람" },
  { word: "amplify", meaning: "확대하다, 증폭하다" },
  { word: "contradict", meaning: "반박하다" },
  { word: "cast", meaning: "던지다" },
  { word: "falsify", meaning: "위조하다" },
  { word: "paddle", meaning: "노, 노를 젓다" },
  { word: "steer", meaning: "조종하다" },
  { word: "affection", meaning: "애정" },
  { word: "bid", meaning: "입찰하다" },
  { word: "temperament", meaning: "기질" },
  { word: "shred", meaning: "갈기갈기 찢다" },
  { word: "unpredictable", meaning: "예측할 수 없는" },
  { word: "artery", meaning: "동맥" },
  { word: "inherent", meaning: "내재된" },
  { word: "harass", meaning: "괴롭히다" },
  { word: "assemble", meaning: "모으다, 조립하다" },
  { word: "spike", meaning: "못, 대못" },
  { word: "sneak", meaning: "몰래 움직이다" },
  { word: "sophisticated", meaning: "정교한, 세련된" },
  { word: "enlightenment", meaning: "계몽, 깨달음" },
  { word: "cosmetic", meaning: "화장품" },
  { word: "aspire", meaning: "열망하다" },
  { word: "obstruct", meaning: "방해하다" },
  { word: "veteran", meaning: "베테랑" },
  { word: "decode", meaning: "해독하다" },
  { word: "mandate", meaning: "명령, 명령하다" },
  { word: "perish", meaning: "죽다, 소멸하다" },
  { word: "penetrate", meaning: "침투하다, 꿰뚫다" },
  { word: "intrude", meaning: "방해하다, 침범하다" },
  { word: "notable", meaning: "주목할 만한" },
  { word: "grumble", meaning: "불평하다, 으르렁거리다" },
  { word: "landfill", meaning: "쓰레기 매립지" },
  { word: "scrutiny", meaning: "면밀한 조사" },
  { word: "reckless", meaning: "부주의한, 무모한" },
  { word: "synthetic", meaning: "합성의" },
  { word: "productive", meaning: "생산적인, 다산의" },
  { word: "outset", meaning: "착수, 시작" },
  { word: "peril", meaning: "위험, 위기" },
  { word: "pitfall", meaning: "함정, 위험" },
  { word: "kidnap", meaning: "유괴하다, 납치하다" },
  { word: "liable", meaning: "책임이 있는, ~하기 쉬운" },
  { word: "insane", meaning: "정신 이상의, 비상식적인" },
  { word: "rage", meaning: "격노, 분노" },
  { word: "radius", meaning: "반지름" },
  { word: "hybrid", meaning: "혼합물, 잡종" },
  { word: "uncover", meaning: "폭로하다, 알아내다" },
  { word: "limb", meaning: "사지, 팔다리" },
  { word: "setback", meaning: "좌절, 차질" },
  { word: "prudent", meaning: "신중한, 빈틈없는" },
  { word: "solidify", meaning: "굳어지다, 확고히 하다" },
  { word: "grudge", meaning: "원한, 유감" },
  { word: "lessen", meaning: "줄이다" },
  { word: "nullify", meaning: "무효화하다, 혼란시키다" },
  { word: "subsidy", meaning: "보조금, 장려금" },
  { word: "ambiguous", meaning: "애매모호한, 두 가지 뜻으로 해석 가능한" },
  { word: "enthusiasm", meaning: "열광, 열정" },
  { word: "bankruptcy", meaning: "파산" },
  { word: "pollination", meaning: "수분 (식물)" },
  { word: "prosper", meaning: "번영하다, 번창하다" },
  { word: "phase", meaning: "단계, 양상" },
  { word: "veterinarian", meaning: "수의사" },
  { word: "counterattack", meaning: "반격, 역습" },
  { word: "cumulative", meaning: "누적되는, 점증적인" },
  { word: "infrastructure", meaning: "사회 기반 시설" },
  { word: "wound", meaning: "부상, 부상하게 하다" },
  { word: "discrete", meaning: "분리된, 별개의" },
  { word: "fluctuation", meaning: "변동, 요동" },
];