const quizData = [
  { word: "apologize", meaning: "[동] 사과하다." },
  { word: "criminal", meaning: "[명][동] 범인; 범죄의." },
  { word: "established", meaning: "[형] 기정의; 설립된; 인정된." },
  { word: "aggravate", meaning: "[동] 악화시키다." },
  { word: "abstain", meaning: "[동] 삼가다; 금주하다." },
  { word: "genetics", meaning: "[명] 유전학." },
  { word: "injustice", meaning: "[명] 부정, 불법, 불공평." },
  { word: "monastery", meaning: "[명] 수도원." },
  { word: "pilgrim", meaning: "[명][형] 순례자; 순례의." },
  { word: "reserved", meaning: "[형] 보류된; 예약의." },
  { word: "striking", meaning: "[형] 두드러진; 파업 중인." },
  { word: "waver", meaning: "[동] 흔들리다." },
  { word: "allusion", meaning: "[명] 암시." },
  { word: "bizarre", meaning: "[형] 기괴한." },
  { word: "chord", meaning: "[명] (악기의) 현; 심금." },
  { word: "convict", meaning: "[동] 유죄를 입증하다." },
  { word: "delineate", meaning: "[동] 윤곽을 그리다." },
  { word: "dub", meaning: "[동] (이름을) 붙이다." },
  { word: "fanatic", meaning: "[형][명] 광적인; 광신자." },
  { word: "hazy", meaning: "[형] 흐린, 안개 낀." },
  { word: "inert", meaning: "[형] 생기 없는; 둔한." },
  { word: "kidney", meaning: "[명] 신장, 콩팥." },
  { word: "momentary", meaning: "[형] 순간의, 순간적인." },
  { word: "pageant", meaning: "[명] 야외극; 화려한 행렬." },
  { word: "postage", meaning: "[명] 우편 요금." },
  { word: "reciprocal", meaning: "[형] 상호의, 호혜적인." },
  { word: "retaliate", meaning: "[동] 보복하다." },
  { word: "slack", meaning: "[형] 느긋한; 꾸물거리는." },
  { word: "swish", meaning: "[동][명] 날갯짓하다; 휙휙 소리." },
  { word: "vend", meaning: "[동] 팔다, 판매하다." },
  { word: "refund", meaning: "[명] 반환." },
  { word: "benefactor", meaning: "[명] 은인; 자선가." },
  { word: "chromatic", meaning: "[형] 색채의; 채색한." },
  { word: "copyright", meaning: "[명] 판권; 저작권." },
  { word: "permit", meaning: "[명] 허가증." },
  { word: "enzyme", meaning: "[명] 효소." },
  { word: "gaunt", meaning: "[형] 수척한; 황량한." },
  { word: "impeccable", meaning: "[형] 흠 없는; 나무랄 데 없는." },
  { word: "landfill", meaning: "[명] 쓰레기 매립지." },
  { word: "peril", meaning: "[명][동] 위험; 위험에 빠뜨리다." },
  { word: "shawl", meaning: "[명] 숄, 어깨걸이." },
  { word: "transient", meaning: "[형] 일시적인; 덧없는." },
  { word: "bow", meaning: "[명] 활." },
  { word: "atop", meaning: "[전] ~의 정상에." },
  { word: "bygone", meaning: "[형][명] 지나간; 과거사." },
  { word: "cuddle", meaning: "[동] 부둥켜안다." },
  { word: "downturn", meaning: "[명] 하강, 침체." },
  { word: "genocide", meaning: "[명] 대량 학살." },
  { word: "mutate", meaning: "[동] 변화하다; 돌연변이하다." },
  { word: "salute", meaning: "[동] 경례하다." },
  { word: "credit", meaning: "[명][동] 신용; 신뢰하다." },
  { word: "objection", meaning: "[명] 반대; 반감." },
  { word: "excess", meaning: "[명] 초과." },
  { word: "arbitrary", meaning: "[형] 임의의; 독단적인." },
  { word: "amendment", meaning: "[명] 개정, 수정." },
  { word: "giggle", meaning: "[동] 낄낄 웃다." },
  { word: "innocuous", meaning: "[형] 독 없는; 무해한." },
  { word: "mortgage", meaning: "[명] 저당." },
  { word: "pious", meaning: "[형] 경건한; 신앙심 깊은." },
  { word: "respectable", meaning: "[형] 존경할 만한." },
  { word: "sturdy", meaning: "[형] 건장한; 억센." },
  { word: "zoom", meaning: "[명][동] 급등; 급등하다." },
  { word: "altruism", meaning: "[명] 이타주의." },
  { word: "bleak", meaning: "[형] 황폐한." },
  { word: "circulation", meaning: "[명] 순환, 유통." },
  { word: "coordinator", meaning: "[명] 조정자." },
  { word: "deluge", meaning: "[명][동] 대홍수; 침수시키다." },
  { word: "efface", meaning: "[동] 지우다, 삭제하다." },
  { word: "faraway", meaning: "[형] 먼; 멀리 떨어진." },
  { word: "heighten", meaning: "[동] 높이다; 강화하다." },
  { word: "inflation", meaning: "[명] 통화 팽창, 인플레이션." },
  { word: "lame", meaning: "[형] 절름발이의; 불구의." },
  { word: "momentous", meaning: "[형] 중대한." },
  { word: "panorama", meaning: "[명] 전경; 파노라마." },
  { word: "pragmatic", meaning: "[형] 실용적인." },
  { word: "reckon", meaning: "[동] 세다; 간주하다." },
  { word: "retract", meaning: "[동] 수축시키다; 취소하다." },
  { word: "slander", meaning: "[명][동] 비방; 헐뜯다." },
  { word: "synthetic", meaning: "[형] 종합의; 합성의." },
  { word: "ventilation", meaning: "[명] 통풍." },
  { word: "alongside", meaning: "[부] 나란히." },
  { word: "bestow", meaning: "[동] 수여하다; 부여하다." },
  { word: "chronology", meaning: "[명] 연대기, 연표." },
  { word: "corridor", meaning: "[명] 복도." },
  { word: "discredit", meaning: "[명][동] 불신; 의심하다." },
  { word: "epoch", meaning: "[명] 새 시대; 획기적인 사건." },
  { word: "gem", meaning: "[명] 보석." },
  { word: "impel", meaning: "[동] 재촉하다." },
  { word: "leash", meaning: "[명] 가죽 끈; 속박." },
  { word: "perpetuate", meaning: "[동] 영원하게 하다." },
  { word: "shove", meaning: "[동] 떠밀다." },
  { word: "treason", meaning: "[명] 배신; 반역." },
  { word: "drawer", meaning: "[명] 서랍." },
  { word: "atrocity", meaning: "[명] 잔인, 흉악." },
  { word: "captive", meaning: "[명][형] 포로; 포로의." },
  { word: "cuff", meaning: "[명] 소매끝단, 커프스; 수갑." },
  { word: "earning", meaning: "[명] 소득." },
  { word: "gladiator", meaning: "[명] 검투사." },
  { word: "muzzle", meaning: "[명][동] 주둥이; 총구; 입막음 하다." },
  { word: "scroll", meaning: "[명][동] 두루마리; 말다." },
  { word: "male", meaning: "[형] 남성의, 수컷의." },
  { word: "orphanage", meaning: "[명] 고아원." },
  { word: "personnel", meaning: "[명][형] 전 직원; 직원의." },
  { word: "assimilate", meaning: "[동] 흡수하다; 동화하다." },
  { word: "appease", meaning: "[동] 달래다, 진정시키다." },
  { word: "grumble", meaning: "[동] 투덜대다; 불평하다." },
  { word: "inquiry", meaning: "[명] 문의; 조사." },
  { word: "narrator", meaning: "[명] 해설자." },
  { word: "plausible", meaning: "[형] 그럴듯한." },
  { word: "retrieve", meaning: "[동] 만회하다; 생각해 내다." },
  { word: "subordinate", meaning: "[형] 하위의, 예하의; 종속의." },
  { word: "crate", meaning: "[명] 나무틀." },
  { word: "amber", meaning: "[명] 호박, 황갈색." },
  { word: "boomerang", meaning: "[명][동] 자업자득; 되돌아오다." },
  { word: "circumscribe", meaning: "[동] 경계를 긋다; 제한하다." },
  { word: "cordial", meaning: "[형] 충심의; 간곡한." },
  { word: "demise", meaning: "[명] 서거; 소멸." },
  { word: "eject", meaning: "[동] 쫓아내다; 배설하다." },
  { word: "fetus", meaning: "[명] 태아." },
  { word: "hereditary", meaning: "[형] 유전의." },
  { word: "ingenuous", meaning: "[형] 솔직한; 순진한." },
  { word: "landslide", meaning: "[명] 산사태; 압도적 승리." },
  { word: "monetary", meaning: "[형] 화폐의." },
  { word: "parable", meaning: "[명] 우화." },
  { word: "preclude", meaning: "[동] 제외하다; 방해하다." },
  { word: "recluse", meaning: "[형][명] 은둔한; 은둔자." },
  { word: "retrospect", meaning: "[명][동] 회고; 회고하다." },
  { word: "slavery", meaning: "[명] 노예 상태, 노예제." },
  { word: "tacit", meaning: "[형] 무언의; 침묵의." },
  { word: "verbose", meaning: "[형] 말 많은; 장황한." },
  { word: "ammunition", meaning: "[명] 탄약." },
  { word: "biosphere", meaning: "[명] 생물권." },
  { word: "addict", meaning: "[동] 중독 시키다." },
  { word: "counteract", meaning: "[동] 방해하다, 거스르다." },
  { word: "discrepancy", meaning: "[명] 불일치." },
  { word: "equation", meaning: "[명] 균등화; 방정식." },
  { word: "ghetto", meaning: "[명] 빈민가; 슬럼가." },
  { word: "impersonal", meaning: "[형] 비인격적인; 비 인칭의." },
  { word: "legendary", meaning: "[형] 전설적인." },
  { word: "philharmonic", meaning: "[형] 음악 애호의; 교향악단의." },
  { word: "shroud", meaning: "[명] 수의; 덮개." },
  { word: "trek", meaning: "[동][명] (소가) 수레를 끌다; 여행." },
  { word: "advantageous", meaning: "[형] 유리한, 이로운." },
  { word: "attenuate", meaning: "[동] 희석시키다." },
  { word: "catharsis", meaning: "[명] (감정의) 정화, 카타르시스." },
  { word: "culinary", meaning: "[형] 부엌의; 요리의." },
  { word: "dreary", meaning: "[형] 황량한; 처량한." },
  { word: "glossary", meaning: "[명] 어휘; 용어풀이." },
  { word: "omen", meaning: "[명] 전조, 징조." },
  { word: "serpent", meaning: "[명] 뱀." },
  { word: "abuse", meaning: "[동] 학대하다." },
  { word: "poisonous", meaning: "[형] 유독한." },
  { word: "possession", meaning: "[명] 소유; 소유물." },
  { word: "asthma", meaning: "[명] 천식." },
  { word: "applaud", meaning: "[동] 박수갈채를 보내다." },
  { word: "harass", meaning: "[동] 괴롭히다; 희롱하다." },
  { word: "instructive", meaning: "[형] 교훈적인." },
  { word: "nausea", meaning: "[명] 메스꺼움." },
  { word: "pluck", meaning: "[동] 잡아 뽑다." },
  { word: "revolve", meaning: "[동] 회전하다." },
  { word: "suffice", meaning: "[동] 충분하다." },
  { word: "farmland", meaning: "[명] 농지." },
  { word: "ambiguity", meaning: "[명] 모호함." },
  { word: "boost", meaning: "[동][명] 추진하다; 후원하다; 추진." },
  { word: "clam", meaning: "[명] 대합조개." },
  { word: "corporal", meaning: "[형][명] 육체의; 상병." },
  { word: "density", meaning: "[명] 밀도." },
  { word: "elucidate", meaning: "[동] 명확히 하다; 설명하다." },
  { word: "feud", meaning: "[명][동] 불화; 반목하다." },
  { word: "hermit", meaning: "[명] 은둔자; 수행자." },
  { word: "inhabit", meaning: "[동] 살다, 거주하다." },
  { word: "lax", meaning: "[형] 느슨한." },
  { word: "morality", meaning: "[명] 도덕; 도덕성." },
  { word: "parasite", meaning: "[명] 기생 동물." },
  { word: "precursor", meaning: "[명] 선구자." },
  { word: "redeem", meaning: "[동] 되찾다; 벌충하다." },
  { word: "revelation", meaning: "[명] 폭로." },
  { word: "slay", meaning: "[동] 살해하다." },
  { word: "talkative", meaning: "[형] 수다스런, 말 많은." },
  { word: "verdict", meaning: "[명] (배심원의) 평결." },
  { word: "amphibian", meaning: "[형] 양서류의; 수륙양용의." },
  { word: "blackout", meaning: "[명] 정전." },
  { word: "circumspect", meaning: "[형] 신중한, 용의주도한." },
  { word: "crag", meaning: "[명] 울통불퉁한 바위." },
  { word: "disgrace", meaning: "[명][동] 불명예; 망신시키다." },
  { word: "esoteric", meaning: "[형] 비법의; 은밀한." },
  { word: "gland", meaning: "[명] 분비기관." },
  { word: "imprisonment", meaning: "[명] 투옥." },
  { word: "lieutenant", meaning: "[명] 중위, 부관." },
  { word: "phonetic", meaning: "[형] 음성의; 음성학의." },
  { word: "solicit", meaning: "[동] 간청하다." },
  { word: "trifle", meaning: "[명] 하찮은 것." },
  { word: "floral", meaning: "[형] 꽃의." },
  { word: "aural", meaning: "[형] 귀의; 청각의." },
  { word: "generator", meaning: "[명] 발전기." },
  { word: "cumbersome", meaning: "[형] 성가신; 주책 맞은." },
  { word: "duel", meaning: "[명] 결투; 시합." },
  { word: "gradation", meaning: "[명] 점진적 변화." },
  { word: "opus", meaning: "[명] 저작; (음악) 작품." },
  { word: "neighborhood", meaning: "[명] 이웃." },
  { word: "politics", meaning: "[명] 정치; 정치학." },
  { word: "procession", meaning: "[명] 행진, 행렬." },
  { word: "throb", meaning: "[동] 두근거리다, 고동치다." },
  { word: "attendance", meaning: "[명] 출석; 시중, 돌봄." },
  { word: "hatred", meaning: "[명] 증오." },
  { word: "insufficient", meaning: "[형] 불충분한." },
  { word: "needy", meaning: "[형] 가난한, 궁핍한." },
  { word: "plumber", meaning: "[명] 배관공." },
  { word: "roam", meaning: "[동] 배회하다." },
  { word: "sullen", meaning: "[형] 뚱한, 무뚝뚝한." },
  { word: "adjourn", meaning: "[동] (회의를) 연기하다." },
  { word: "ameliorate", meaning: "[동] 개선하다." },
  { word: "ceaseless", meaning: "[형] 끊임없는." },
  { word: "clause", meaning: "[명] 조항; 절." },
  { word: "corroborate", meaning: "[동] 확실히 하다." },
  { word: "depot", meaning: "[명] 저장고; 차고." },
  { word: "elude", meaning: "[동] 회피하다." },
  { word: "fitness", meaning: "[명] 적합; 타당성." },
  { word: "hoarse", meaning: "[형] 목이 쉰; 귀에 거슬리는." },
  { word: "innocence", meaning: "[명] 순진; 결벽; 순결." },
  { word: "lethargy", meaning: "[명] 혼수상태; 무기력." },
  { word: "municipal", meaning: "[형] 도시의." },
  { word: "parish", meaning: "[명] (교회) 본당, 교구." },
  { word: "predator", meaning: "[명] 약탈자." },
  { word: "redundant", meaning: "[형] 여분의." },
  { word: "revision", meaning: "[명] 개정; 교열." },
  { word: "solace", meaning: "[명] 위안, 위로." },
  { word: "tan", meaning: "[동] 무두질하다; 햇볕에 태우다." },
  { word: "versus", meaning: "[전] ~대." },
  { word: "amputate", meaning: "[동] 손, 발을 절단하다." },
  { word: "adversary", meaning: "[명][형] 적; 상대; 반대하는." },
  { word: "civic", meaning: "[형] 시민의." },
  { word: "creek", meaning: "[명] 시내, 샛강." },
  { word: "disillusion", meaning: "[명] 각성; 환멸." },
  { word: "eternity", meaning: "[명] 영원." },
  { word: "glimmer", meaning: "[명][동] 희미한 빛; 깜빡이다." },
  { word: "improper", meaning: "[형] 부적당한." },
  { word: "linguist", meaning: "[명] 언어학자." },
  { word: "pier", meaning: "[명] 부두; 방파제." },
  { word: "speck", meaning: "[명] 반점, 얼룩." },
  { word: "tripod", meaning: "[명] 삼발이." },
  { word: "affectation", meaning: "[명] 가장, 꾸밈." },
  { word: "autocracy", meaning: "[명] 독재정치." },
  { word: "censor", meaning: "[명][동] 검열관; 검열하다." },
  { word: "cutback", meaning: "[명] 삭감." },
  { word: "elation", meaning: "[명] 의기양양." },
  { word: "healthcare", meaning: "[명] 건강관리." },
  { word: "oracle", meaning: "[명] 계시; 예언자." },
  { word: "shimmer", meaning: "[명][동] 희미한 불빛; 반짝이다." },
  { word: "realize", meaning: "[동] 실현하다; 구현하다." },
  { word: "unify", meaning: "[동] 통일하다." },
  { word: "raft", meaning: "[명] 뗏목." },
  { word: "adhesive", meaning: "[형][명] 접착성의; 접착제." },
  { word: "augment", meaning: "[동] 보강하다; 늘리다." },
  { word: "haunt", meaning: "[동] 출몰하다." },
  { word: "intuition", meaning: "[명] 직관, 직감." },
  { word: "negotiate", meaning: "[동] 교섭하다." },
  { word: "poorly", meaning: "[부] 가난하게; 서툴게." },
  { word: "savor", meaning: "[명] 맛, 풍미." },
  { word: "superfluous", meaning: "[형] 넘치는." },
  { word: "ascetic", meaning: "[명][형] 금욕주의자; 금욕주의의." },
  { word: "amnesty", meaning: "[명] 사면, 특사." },
  { word: "brew", meaning: "[동] 양조하다." },
  { word: "clearance", meaning: "[명] 제거; 정리." },
  { word: "corrode", meaning: "[동] 부식하다." },
  { word: "depreciate", meaning: "[동] 평가절하하다; 얕보다." },
  { word: "embassy", meaning: "[명] 대사관." },
  { word: "fixture", meaning: "[명] 정착물; 비품." },
  { word: "horde", meaning: "[명][동] 집단; 무리지어 이동하다." },
  { word: "innovate", meaning: "[동] 혁신하다." },
  { word: "liaison", meaning: "[명] 연락; 연락관." },
  { word: "munificent", meaning: "[형] 인색하지 않은." },
  { word: "parlor", meaning: "[명] 객실; 응접실." },
  { word: "predominant", meaning: "[형] 뛰어난, 눈에 띄는." },
  { word: "refrain", meaning: "[동] 삼가다; 그만두다." },
  { word: "revolt", meaning: "[명] 반란; 폭동." },
  { word: "somber", meaning: "[형] 흐린; 거무스름한." },
  { word: "tangible", meaning: "[형] 만질 수 있는." },
  { word: "veteran", meaning: "[명] 퇴역 군인; 경험 많은 사람." },
  { word: "anachronism", meaning: "[명] 시대착오." },
  { word: "blur", meaning: "[명][동] 얼룩; 희미해지다." },
  { word: "civilian", meaning: "[명][형] 민간인; 민간인의." },
  { word: "crimson", meaning: "[명][형] 핏빛, 심홍색; 피로 물들인." },
  { word: "disparity", meaning: "[명] 불균형; 불일치." },
  { word: "eulogy", meaning: "[명] 찬미, 칭송." },
  { word: "gloss", meaning: "[명][동] 윤; 주석; 윤을 내다." },
  { word: "inability", meaning: "[명] 무능력." },
  { word: "lurk", meaning: "[동] 숨다; 잠복하다." },
  { word: "poignant", meaning: "[형] 매서운; 날카로운." },
  { word: "spike", meaning: "[명] 대못." },
  { word: "tug", meaning: "[동] 당기다, 끌다." },
  { word: "affix", meaning: "[동][명] 첨부하다; 첨부물." },
  { word: "balk", meaning: "[동][명] 방해하다; 훼방." },
  { word: "chronicle", meaning: "[명] 연대기." },
  { word: "daunting", meaning: "[형] 무서운; 위압적인." },
  { word: "electorate", meaning: "[명] 유권자." },
  { word: "hurl", meaning: "[동] 집어던지다." },
  { word: "oration", meaning: "[명] 연설; 화법." },
  { word: "slump", meaning: "[명] 폭락; 부진상태." },
  { word: "accuse", meaning: "[동] 고소하다; 비난하다." },
  { word: "desperate", meaning: "[형] 필사적인; 절망적인." },
  { word: "reunion", meaning: "[명] 재결합." },
  { word: "coincide", meaning: "[동] 동시에 발생하다." },
  { word: "awaken", meaning: "[동] 깨우다; 각성시키다." },
  { word: "headquarters", meaning: "[명] 본부, 본사." },
  { word: "invert", meaning: "[동] 거꾸로 하다, 뒤집다." },
  { word: "nuance", meaning: "[명] 미묘한 차이, 뉘앙스." },
  { word: "posture", meaning: "[명] 자세." },
  { word: "scarcely", meaning: "[부] 거의 ~ 아니다." },
  { word: "supernatural", meaning: "[형] 초자연적인." },
  { word: "desolate", meaning: "[형] 황폐한; 쓸쓸한." },
  { word: "amorphous", meaning: "[형] 정해진 형태가 없는." },
  { word: "bristle", meaning: "[동] (털이) 곤두서다; 화내다." },
  { word: "clergy", meaning: "[명] 성직자." },
  { word: "cosmic", meaning: "[형] 우주의." },
  { word: "detach", meaning: "[동] 떼다." },
  { word: "embody", meaning: "[동] 구체화하다." },
  { word: "flatten", meaning: "[동] 평평하게 하다." },
  { word: "humiliate", meaning: "[동] 모욕을 주다; 욕보이다." },
  { word: "insane", meaning: "[형] 미친." },
  { word: "lively", meaning: "[형] 생기 넘치는." },
  { word: "mythology", meaning: "[명] 신화." },
  { word: "parody", meaning: "[명] (풍자식의) 모방." },
  { word: "preposterous", meaning: "[형] 앞뒤가 바뀐; 터무니없는." },
  { word: "regain", meaning: "[동] 되찾다; 회복하다." },
  { word: "robust", meaning: "[형] 튼튼한." },
  { word: "spatial", meaning: "[형] 공간의." },
  { word: "tenor", meaning: "[명] 방침; 테너." },
  { word: "vex", meaning: "[동] 귀찮게 하다; 괴롭히다." },
  { word: "object", meaning: "[동] 반대하다." },
  { word: "bombast", meaning: "[명] 과장, 호언장담." },
  { word: "climax", meaning: "[명] 절정, 클라이맥스." },
  { word: "crossroad", meaning: "[명] 십자로, 교차로." },
  { word: "dispatch", meaning: "[동] 파병하다." },
  { word: "evince", meaning: "[동] 명시하다; 표시하다." },
  { word: "granite", meaning: "[명] 화강암." },
  { word: "inaccurate", meaning: "[형] 부정확한." },
  { word: "mast", meaning: "[동] 돛대." },
  { word: "portend", meaning: "[동] 미리 알리다, 전조가 되다." },
  { word: "sprint", meaning: "[명][동] 전력 질주; 역주하다." },
  { word: "tuition", meaning: "[명] 수업, 교수." },
  { word: "affluent", meaning: "[형] 풍부한." },
  { word: "ballistic", meaning: "[형] 탄도의." },
  { word: "cliche", meaning: "[명] 진부한 표현, 상투적인 말." },
  { word: "debunk", meaning: "[동] 폭로하다." },
  { word: "emanate", meaning: "[동] 발산하다." },
  { word: "hypnosis", meaning: "[명] 최면; 최면술." },
  { word: "ordnance", meaning: "[명] 병기; 군수품." },
  { word: "smack", meaning: "[명][동] 향기; 낌새; 세게 때리다." },
  { word: "firm", meaning: "[형][명] 굳은; 확고한; 회사." },
  { word: "formation", meaning: "[명] 형성." },
  { word: "sanction", meaning: "[명][동] 인가; 제재; 제재하다." },
  { word: "dread", meaning: "[동][명] 두려워하다; 공포." },
  { word: "blaze", meaning: "[명][동] 불길; 타오르다; 격노하다." },
  { word: "heed", meaning: "[명][동] 주의; 주의하다." },
  { word: "invigorate", meaning: "[동] 원기를 돋우다." },
  { word: "nymph", meaning: "[명] 요정, 님프." },
  { word: "predecessor", meaning: "[명] 전임자, 선배." },
  { word: "scribble", meaning: "[명] 휘갈겨 쓰기, 악필." },
  { word: "surmise", meaning: "[명][동] 추측; 추측하다." },
  { word: "deteriorate", meaning: "[동] 악화시키다; 타락시키다." },
  { word: "angular", meaning: "[형] 모난; 각을 이룬." },
  { word: "brittle", meaning: "[형] 부서지기 쉬운." },
  { word: "clout", meaning: "[명] 영향력; 타격." },
  { word: "cosmopolitan", meaning: "[형] 세계를 활동 무대로 삼는." },
  { word: "detrimental", meaning: "[형] 해로운." },
  { word: "emigrate", meaning: "[동] (타국으로) 이주하다." },
  { word: "flux", meaning: "[명] 흐름; 유출." },
  { word: "hunchback", meaning: "[명] 곱사등이, 꼽추." },
  { word: "inscribe", meaning: "[동] (비석 등에) 새기다." },
  { word: "loath", meaning: "[형] 싫어하는, 질색하는." },
  { word: "navigate", meaning: "[동] 항해하다; 조종하다." },
  { word: "pebble", meaning: "[명] 조약돌." },
  { word: "priceless", meaning: "[형] 귀중한, 값을 매길 수 없는." },
  { word: "reinforce", meaning: "[동] 강화하다." },
  { word: "rotation", meaning: "[명] 회전; 순환." },
  { word: "spine", meaning: "[명] 등뼈, 척추." },
  { word: "terse", meaning: "[형] 간결한." },
  { word: "vilify", meaning: "[동] 헐뜯다." },
  { word: "aerial", meaning: "[형] 공기의; 항공의." },
  { word: "botany", meaning: "[명] 식물학." },
  { word: "clog", meaning: "[동][명] 방해하다; 장애물." },
  { word: "crumple", meaning: "[동][명] 구기다; 구김살." },
  { word: "dissect", meaning: "[동] 해부하다." },
  { word: "expenditure", meaning: "[명] 지출, 소비." },
  { word: "increase", meaning: "[명] 증가." },
  { word: "inaugural", meaning: "[형] 취임의, 취임식의." },
  { word: "metropolis", meaning: "[명] 수도; 대도시." },
  { word: "posterity", meaning: "[명] 후손, 자손." },
  { word: "stagnant", meaning: "[형] 정체된; 불경기의." },
  { word: "turbulent", meaning: "[형] 사나운, 거친." },
  { word: "elaborate", meaning: "[형] 정교한." },
  { word: "bandit", meaning: "[명] 강도, 산적." },
  { word: "cloak", meaning: "[명] 외투; 망토." },
  { word: "debut", meaning: "[명][동] 데뷔; 데뷔하다." },
  { word: "embezzlement", meaning: "[명] 횡령." },
  { word: "illicit", meaning: "[형] 불법의, 부정한." },
  { word: "paradoxical", meaning: "[형] 역설적인." },
  { word: "snore", meaning: "[명][동] 코골이; 코를 골다." },
  { word: "loyal", meaning: "[형] 충성스러운, 성실한." },
  { word: "surgery", meaning: "[명] 외과; 수술." },
  { word: "ally", meaning: "[명] 동맹국." },
  { word: "economics", meaning: "[명] 경제학." },
  { word: "blemish", meaning: "[명][동] 오점; 오점을 남기다." },
  { word: "hideous", meaning: "[형] 섬뜩한, 무시무시한." },
  { word: "irrational", meaning: "[형] 불합리한." },
  { word: "odor", meaning: "[명] 냄새; 향기." },
  { word: "prehistoric", meaning: "[형] 선사시대의." },
  { word: "seep", meaning: "[동] 스며 나오다." },
  { word: "suspense", meaning: "[명] 미결정; 걱정, 불안." },
  { word: "deviate", meaning: "[동] 일탈하다, 벗어나다." },
  { word: "array", meaning: "[동][명] 정렬시키다; 정렬." },
  { word: "separate", meaning: "[형] 분리된." },
  { word: "clutch", meaning: "[동][명] 꽉 쥐다; (차의) 클러치." },
  { word: "counter", meaning: "[명][형] 계산대; 반대의." },
  { word: "dilettante", meaning: "[명] 아마추어 애호가." },
  { word: "emulate", meaning: "[동] 겨루다; 흉내 내다." },
  { word: "foresee", meaning: "[동] 예견하다." },
  { word: "hymn", meaning: "[명] 찬송가." },
  { word: "insignificant", meaning: "[형] 무의미한." },
  { word: "longitude", meaning: "[명] (지리의) 경도." },
  { word: "nomad", meaning: "[명][형] 유목민; 방랑하는." },
  { word: "peep", meaning: "[동] 엿보다." },
  { word: "pristine", meaning: "[형] 원시의; 순박한." },
  { word: "reiterate", meaning: "[동] 되풀이하다, 반복하다." },
  { word: "resume", meaning: "[명] 이력서." },
  { word: "spiral", meaning: "[형] 나선형의." },
  { word: "testify", meaning: "[동] 증언하다." },
  { word: "virgin", meaning: "[명][형] 처녀; 처녀의." },
  { word: "antagonist", meaning: "[명] 적수, 적대자." },
  { word: "brace", meaning: "[명][동] 지주, 받침대; 떠받치다." },
  { word: "cocoon", meaning: "[명] 고치." },
  { word: "extract", meaning: "[명] 발췌; 추출물." },
  { word: "dissonance", meaning: "[명] 불협화음; 부조화." },
  { word: "extrinsic", meaning: "[형] 외부의; 비본질적인." },
  { word: "guardian", meaning: "[동] 수호자; 후견인." },
  { word: "inconsistent", meaning: "[형] 일치하지 않는, 모순된." },
  { word: "mingle", meaning: "[동] 섞다, 혼합하다." },
  { word: "precision", meaning: "[명] 정밀, 정확." },
  { word: "stalemate", meaning: "[명] 막다름, 궁지." },
  { word: "tyranny", meaning: "[명] 폭정, 전제정치." },
  { word: "agrarian", meaning: "[형] 토지의, 농업의." },
  { word: "compound", meaning: "[형][명] 합성의; 화합물." },
  { word: "close-up", meaning: "[명] 근접 사진, 클로즈업." },
  { word: "decease", meaning: "[명][동] 사망; 사망하다." },
  { word: "encode", meaning: "[동] 암호화하다." },
  { word: "imperil", meaning: "[동] 위태롭게 하다." },
  { word: "partake", meaning: "[동] 참가하다." },
  { word: "subterranean", meaning: "[형] 지하의." },
  { word: "refrigerator", meaning: "[명] 냉장고." },
  { word: "therapy", meaning: "[명] 치료." },
  { word: "gear", meaning: "[명] 전동장치; 기구." },
  { word: "blink", meaning: "[동][명] (눈을) 깜박이다; 깜박임." },
  { word: "homage", meaning: "[명] 존경; 경의." },
  { word: "irrigate", meaning: "[동] 물을 대다, 관개하다." },
  { word: "omission", meaning: "[명] 생략; 태만." },
  { word: "premise", meaning: "[명][동] 전제; 제언하다." },
  { word: "segregate", meaning: "[동] 분리하다." },
  { word: "symmetry", meaning: "[명] 대칭; 균형." },
  { word: "devour", meaning: "[동] 게걸스레 먹다." },
  { word: "ascribe", meaning: "[동] ~의 탓으로 돌리다." },
  { word: "cogent", meaning: "[형] 적절한; 설득력 있는." },
  { word: "craftsman", meaning: "[명] 장인." },
  { word: "dimple", meaning: "[명] 보조개." },
  { word: "encircle", meaning: "[동] 에워싸다, 둘러싸다." },
  { word: "forgo", meaning: "[동] ~없이 지내다." },
  { word: "hysteria", meaning: "[명] 히스테리, 병적흥분." },
  { word: "insolent", meaning: "[형] 거만한, 뻐기는." },
  { word: "lost", meaning: "[형] 행방불명의; 타락한." },
  { word: "notable", meaning: "[형] 주목할 만한." },
  { word: "penchant", meaning: "[명] 경향, 취향." },
  { word: "profuse", meaning: "[형] 통이 큰, 후한." },
  { word: "relativity", meaning: "[명] 상대성, 관련성." },
  { word: "ruffle", meaning: "[동][명] 어지럽히다; 동요." },
  { word: "stagger", meaning: "[동] 비틀거리다." },
  { word: "threshold", meaning: "[명] 문지방." },
  { word: "vogue", meaning: "[명][형] 유행; 유행하는." },
  { word: "antibody", meaning: "[명] 항체." },
  { word: "brag", meaning: "[동][명] 자랑하다; 허풍 떨다; 자랑." },
  { word: "cohesive", meaning: "[형] 밀착하는; 응집력의." },
  { word: "culminate", meaning: "[동] 정점에 이르다." },
  { word: "dividend", meaning: "[명] 배당금; 몫." },
  { word: "extrovert", meaning: "[명] 외향적인 사람." },
  { word: "gulp", meaning: "[동] 꿀꺽 마시다; 삼키다." },
  { word: "incumbent", meaning: "[형] 현직의." },
  { word: "mop", meaning: "[명][동] 자루걸레; 청소하다." },
  { word: "precocious", meaning: "[형] 조숙한." },
  { word: "standpoint", meaning: "[명] 입장, 관점." },
  { word: "unison", meaning: "[명] 조화; 제창." },
  { word: "algae", meaning: "[명] 조류." },
  { word: "barb", meaning: "[명][동] 가시; 가시를 달다." },
  { word: "clot", meaning: "[명][동] 덩어리, 응고; 응고되다." },
  { word: "decompose", meaning: "[동] 분해하다; 부패시키다." },
  { word: "enslave", meaning: "[동] 노예로 만들다." },
  { word: "implant", meaning: "[동] 심다; 이식하다." },
  { word: "pastoral", meaning: "[형] 전원의; 목가적인." },
  { word: "syndicate", meaning: "[명] 기업 연합, 신디케이트." },
  { word: "extenuate", meaning: "[동] 경감하다; 정상을 참작하다." },
  { word: "disability", meaning: "[명] (신체) 장애, 불구." },
  { word: "vary", meaning: "[동] 다양하게 하다." },
  { word: "millionaire", meaning: "[명] 백만장자." },
  { word: "hindrance", meaning: "[명] 방해, 장애." },
  { word: "calamity", meaning: "[명] 재난." },
  { word: "humankind", meaning: "[명] 인류, 인간." },
  { word: "ivory", meaning: "[명] 상아." },
  { word: "ongoing", meaning: "[형] 전진하는, 진행하는." },
  { word: "prestigious", meaning: "[형] 정평이 난, 이름난." },
  { word: "sensible", meaning: "[형] 분별 있는, 양식 있는." },
  { word: "tangle", meaning: "[동][명] 엉키게 하다; 혼란." },
  { word: "broker", meaning: "[명] 중개인." },
  { word: "aspiration", meaning: "[명] 열망." },
  { word: "broth", meaning: "[명] 묽은 수프, 국." },
  { word: "cognizant", meaning: "[형] 인식하고 있는." },
  { word: "credential", meaning: "[명] 자격 증명서; 신임장." },
  { word: "disciple", meaning: "[명] 제자, 문하생." },
  { word: "encroach", meaning: "[동] 침입하다, 잠식하다." },
  { word: "formidable", meaning: "[형] 무서운, 강력한." },
  { word: "immerse", meaning: "[동] (물 등에) 담그다." },
  { word: "integration", meaning: "[명] 통합." },
  { word: "lucid", meaning: "[형] 명쾌한, 투명한." },
  { word: "noted", meaning: "[형] 저명한, 유명한." },
  { word: "perfunctory", meaning: "[형] 형식적인; 겉치레의." },
  { word: "prophecy", meaning: "[명] 예언." },
  { word: "relegate", meaning: "[동] 추방하다; 좌천시키다." },
  { word: "sanctuary", meaning: "[명] 거룩한 장소, 성소." },
  { word: "stalk", meaning: "[명] 줄기." },
  { word: "toil", meaning: "[명][동] 수고; 수고하다." },
  { word: "volatile", meaning: "[형] 휘발성의; 변덕스런." },
  { word: "apex", meaning: "[명] 정상, 꼭대기; 최고조." },
  { word: "bravery", meaning: "[명] 용기, 용감." },
  { word: "coil", meaning: "[명][동] 소용돌이; 말다." },
  { word: "dandy", meaning: "[명][형] 멋쟁이; 멋 내는." },
  { word: "dogma", meaning: "[명] 독단적 주장." },
  { word: "fabricate", meaning: "[동] (거짓으로) 꾸며 내다." },
  { word: "halve", meaning: "[동] 반으로 나누다; 줄이다." },
  { word: "ineffective", meaning: "[형] 효과 없는; 쓸모없는." },
  { word: "Muslim", meaning: "[명] 이슬람교도." },
  { word: "prevalent", meaning: "[형] 널리 보급된; 우세한." },
  { word: "starch", meaning: "[명] 녹말, 전분." },
  { word: "insult", meaning: "[명] 모욕." },
  { word: "alienate", meaning: "[동] 따돌리다, 소외시키다." },
  { word: "barefoot", meaning: "[형] 맨발의." },
  { word: "clutter", meaning: "[명][동] 난장판; 난장판으로 만들다." },
  { word: "designate", meaning: "[형] 지정된." },
  { word: "entomology", meaning: "[명] 곤충학." },
  { word: "incarnation", meaning: "[명] 화신; 구체화." },
  { word: "peal", meaning: "[명][동] (종의) 울림; 울리다." },
  { word: "tarnish", meaning: "[동] 변색시키다; 더럽히다." },
  { word: "scary", meaning: "[형] 겁나는; 못생긴." },
  { word: "altitude", meaning: "[명] 높이; 고도." },
  { word: "aggregate", meaning: "[형] 합계의." },
  { word: "inference", meaning: "[명] 추론, 추정." },
  { word: "classified", meaning: "[형] 분류된; 기밀의." },
  { word: "ignite", meaning: "[동] 불을 붙이다." },
  { word: "janitor", meaning: "[명] 문지기; 수위." },
  { word: "opposition", meaning: "[명] 반대." },
  { word: "procure", meaning: "[동] 획득하다." },
  { word: "shabby", meaning: "[형] 초라한, 누더기의." },
  { word: "terminate", meaning: "[동] 끝내다." },
  { word: "abbreviate", meaning: "[동] 줄여서 쓰다, 단축하다." },
  { word: "assent", meaning: "[동][명] 동의하다; 동의, 찬성." },
  { word: "built-in", meaning: "[형] 내장된; 붙박이의." },
  { word: "collective", meaning: "[형] 집단의, 집단적인." },
  { word: "cruelty", meaning: "[명] 잔인; 학대." },
  { word: "discord", meaning: "[명] 불화; 불협화음." },
  { word: "endemic", meaning: "[명][형] 풍토병; 특정 지방의." },
  { word: "fowl", meaning: "[명] 닭; 가금." },
  { word: "impartial", meaning: "[형] 공평한, 치우치지 않은." },
  { word: "intensify", meaning: "[동] 증강하다; 격화시키다." },
  { word: "lucrative", meaning: "[형] 수지맞는; 이익이 되는." },
  { word: "numeral", meaning: "[명][형] 숫자; 수의." },
  { word: "persecute", meaning: "[동] 박해하다." },
  { word: "proprietor", meaning: "[명] 소유자." },
  { word: "reliance", meaning: "[명] 신뢰; 의존." },
  { word: "satire", meaning: "[명] 풍자." },
  { word: "stall", meaning: "[명] 마구간; 매점." },
  { word: "torment", meaning: "[명][동] 고통; 고문; 괴롭히다." },
  { word: "warranty", meaning: "[명] 보증; 보증서." },
  { word: "append", meaning: "[동] 덧붙이다, 추가하다." },
  { word: "brim", meaning: "[명] 가장자리, 언저리." },
  { word: "coma", meaning: "[명] 혼수상태." },
  { word: "deciduous", meaning: "[형] 낙엽성의." },
  { word: "dosage", meaning: "[명] 복용량." },
  { word: "faucet", meaning: "[명] 수도꼭지." },
  { word: "hamper", meaning: "[동] 방해하다." },
  { word: "ineligible", meaning: "[형] 부적격의." },
  { word: "muster", meaning: "[명][동] 소집; 소집하다." },
  { word: "prodigal", meaning: "[형] 방탕한, 낭비하는." },
  { word: "stool", meaning: "[명] (등받이 없는) 의자." },
  { word: "valiant", meaning: "[형] 용감한; 씩씩한." },
  { word: "allure", meaning: "[명] 꾀다, 유혹하다." },
  { word: "battalion", meaning: "[명] (군대의) 대대." },
  { word: "cockpit", meaning: "[명] 조종실." },
  { word: "delinquent", meaning: "[형] 비행의; 직무태만의." },
  { word: "entrepreneur", meaning: "[명] 기업가." },
  { word: "infuse", meaning: "[동] 주입하다." },
  { word: "peddle", meaning: "[동] 행상하다." },
  { word: "telepathy", meaning: "[명] 텔레파시; 이심전심." },
  { word: "gap", meaning: "[명] 틈; 간격; 격차." },
  { word: "whip", meaning: "[명][동] 채찍; 채찍질하다." },
  { word: "dubious", meaning: "[형] 의심스러운." },
  { word: "literary", meaning: "[형] 문학의." },
  { word: "confer", meaning: "[동] 수여하다." },
  { word: "ignorance", meaning: "[명] 무지." },
  { word: "hegemony", meaning: "[명] 패권, 지배권." },
  { word: "orthodox", meaning: "[명][형] 정통파; 정통파의." },
  { word: "prosper", meaning: "[동] 번영하다." },
  { word: "sheer", meaning: "[형][부] 얇은; 순수한; 완전히." },
  { word: "textile", meaning: "[명] 직물." },
  { word: "abdomen", meaning: "[명] 배, 복부." },
  { word: "assiduous", meaning: "[형] 근면한, 부지런한." },
  { word: "burial", meaning: "[명] 매장." },
  { word: "colonel", meaning: "[명] (군대의) 대령." },
  { word: "cuisine", meaning: "[명] 요리; 요리법." },
  { word: "discourse", meaning: "[명][동] 강연; 담화; 강연하다." },
  { word: "engagement", meaning: "[명] 약속; 약혼." },
  { word: "impeach", meaning: "[동] 탄핵하다; 고발하다." },
  { word: "intercept", meaning: "[동] 가로채다." },
  { word: "luminous", meaning: "[형] 빛을 내는." },
  { word: "nursery", meaning: "[명] 보육원; 탁아소." },
  { word: "pervade", meaning: "[동] 널리 퍼지다." },
  { word: "prose", meaning: "[명] 산문." },
  { word: "relish", meaning: "[명] 맛, 풍미; 흥미." },
  { word: "scanty", meaning: "[형] 빈약한; 부족한." },
  { word: "stammer", meaning: "[동] 말을 더듬다." },
  { word: "traitor", meaning: "[명] 배신자; 역적." },
  { word: "wedge", meaning: "[명] 쐐기." },
  { word: "archaic", meaning: "[형] 고풍의, 낡은." },
  { word: "combustion", meaning: "[명] 연소." },
  { word: "deduct", meaning: "[동] 빼다, 공제하다." },
  { word: "droop", meaning: "[동] 시들다, 축 처지다." },
  { word: "fig", meaning: "[동][명] 치장하다; 무화과." },
  { word: "heave", meaning: "[동] 들어 올리다." },
  { word: "ingratiate", meaning: "[동] ~의 비위를 맞추다." },
  { word: "nebula", meaning: "[명] 성운." },
  { word: "prowl", meaning: "[동] 배회하다." },
  { word: "stoop", meaning: "[동] 웅크리다." },
  { word: "venue", meaning: "[명] (행사, 사건의) 현장, 장소." },
  { word: "excerpt", meaning: "[동] 발췌하다." },
  { word: "beacon", meaning: "[명][동] 횃불; 봉화; 인도하다." },
  { word: "coerce", meaning: "[동] 강요하다." },
  { word: "delusion", meaning: "[명] 현혹; 기만." },
  { word: "epilogue", meaning: "[명] 맺음말." },
  { word: "inhale", meaning: "[동] 흡입하다." },
  { word: "pentagon", meaning: "[명] 5각형; 미국국방부." },
  { word: "tempo", meaning: "[명] 빠르기." },
  { word: "apparent", meaning: "[형] 명백한; 외관의." },
  { word: "creativity", meaning: "[명] 창의력, 창조성." },
  { word: "duration", meaning: "[명] 지속." },
  { word: "organism", meaning: "[명] 유기체; 생명체." },
  { word: "contrite", meaning: "[형] 뉘우치는; 회개한." },
  { word: "immaculate", meaning: "[형] 오점 없는; 청순한." },
  { word: "justify", meaning: "[동] 정당화하다." },
  { word: "outbreak", meaning: "[명] (전쟁, 질병의) 발발." },
  { word: "purify", meaning: "[동] 순화하다; 정화하다." },
  { word: "shovel", meaning: "[명] 삽." },
  { word: "thatch", meaning: "[명] 짚; 초가지붕." },
  { word: "aberration", meaning: "[명] 탈선." },
  { word: "attire", meaning: "[명][동] 복장; 차려 입히다." },
  { word: "bypass", meaning: "[명][동] 우회로; 우회하다." },
  { word: "combat", meaning: "[명][동] 전투; 싸우다." },
  { word: "curator", meaning: "[명] 관리자, 큐레이터." },
  { word: "disparage", meaning: "[동] 깔보다; 헐뜯다." },
  { word: "engender", meaning: "[동] 발생시키다; 일으키다." },
  { word: "fragrance", meaning: "[명] 향기." },
  { word: "impede", meaning: "[동] 방해하다." },
  { word: "interlude", meaning: "[명] 막과 막 사이, 막간." },
  { word: "mainland", meaning: "[명] 대륙; 본토." },
  { word: "nutritious", meaning: "[형] 영양분이 있는, 영양의." },
  { word: "pessimistic", meaning: "[형] 비관적인, 염세적인." },
  { word: "publicity", meaning: "[명] 널리 알려짐, 공표." },
  { word: "renounce", meaning: "[동] 포기하다." },
  { word: "scramble", meaning: "[동] 뒤섞다; 기어오르다." },
  { word: "static", meaning: "[형] 정적인." },
  { word: "trite", meaning: "[형] 흔해 빠진, 진부한." },
  { word: "whimsical", meaning: "[형] 변덕스러운." },
  { word: "arduous", meaning: "[형] 힘든; 끈기 있는." },
  { word: "broom", meaning: "[명][동] 빗자루; 비질을 하다." },
  { word: "distortion", meaning: "[명] 왜곡." },
  { word: "default", meaning: "[명] 채무 불이행." },
  { word: "dual", meaning: "[형] 둘의, 이중의." },
  { word: "finale", meaning: "[명] 대단원, 피날레." },
  { word: "hedge", meaning: "[명] 산울타리; 장벽." },
  { word: "insecure", meaning: "[형] 불안정한." },
  { word: "norm", meaning: "[명] 기준; 표준." },
  { word: "puppet", meaning: "[명] 꼭두각시." },
  { word: "stupor", meaning: "[명] 무감각; 마비." },
  { word: "veto", meaning: "[명][동] 거부권; 거부하다." },
  { word: "amenity", meaning: "[명] 쾌적함; 상냥함." },
  { word: "befall", meaning: "[동] 좋지 않은 일이 생기다." },
  { word: "collateral", meaning: "[형][명] 평행한; 부차적인; 담보물." },
  { word: "demean", meaning: "[동] (품위를) 떨어뜨리다." },
  { word: "eugenic", meaning: "[형] 우생의; 우생학의." },
  { word: "inmate", meaning: "[명] 재소자; 입원 환자." },
  { word: "pistol", meaning: "[명] 권총." },
  { word: "tenacity", meaning: "[명] 고집; 끈기." },
  { word: "assign", meaning: "[동] 할당하다; 배당하다." },
  { word: "detective", meaning: "[명][형] 탐정; 형사; 탐정의." },
  { word: "analyst", meaning: "[명] 분석가." },
  { word: "glitch", meaning: "[명] (기계 등의) 결함." },
  { word: "convene", meaning: "[동] (회의 등을) 소집하다." },
  { word: "immature", meaning: "[형] 미숙한." },
  { word: "landing", meaning: "[명] 상륙; 착륙." },
  { word: "outfit", meaning: "[명] 여행 등의 채비; 장비." },
  { word: "radiate", meaning: "[동] 빛을 내다, 방사하다." },
  { word: "shrug", meaning: "[동] (어깨를) 으쓱하다." },
  { word: "theft", meaning: "[명] 도둑질, 절도." },
  { word: "abortion", meaning: "[명] 낙태." },
  { word: "auditorium", meaning: "[명] 강당; 관중석." },
  { word: "cajole", meaning: "[동] 부추기다; 꼬드기다." },
  { word: "complexion", meaning: "[명] 안색; 용모." },
  { word: "deadline", meaning: "[명] 마감 시간, 기한." },
  { word: "disparate", meaning: "[형] 다른; 이종의." },
  { word: "engrave", meaning: "[동] 새겨 넣다, 조각하다." },
  { word: "fugitive", meaning: "[명][형] 도망자; 도망치는." },
  { word: "impromptu", meaning: "[부] 즉흥적으로." },
  { word: "internship", meaning: "[명] 수련 기간; 수련 제도." },
  { word: "marrow", meaning: "[명] 골수; 알짜배기." },
  { word: "observant", meaning: "[형] 관찰력이 있는; 준수하는." },
  { word: "petition", meaning: "[명] 청원; 청원서." },
  { word: "puff", meaning: "[동][명] 훅 불다; 불기." },
  { word: "renovate", meaning: "[동] 혁신하다; 수리하다." },
  { word: "seemingly", meaning: "[부] 외관상으로." },
  { word: "stationary", meaning: "[형] 움직이지 않는, 정지된." },
  { word: "trophy", meaning: "[명] 우승컵; 전리품." },
  { word: "wield", meaning: "[동] (칼, 권력을) 휘두르다." },
  { word: "aristocracy", meaning: "[명] 귀족 정치." },
  { word: "buffer", meaning: "[명][동] 완충장치; 완화하다." },
  { word: "commentary", meaning: "[명] 논평." },
  { word: "deflation", meaning: "[명] 통화수축." },
  { word: "dummy", meaning: "[형][명] 가짜의; 가짜." },
  { word: "flamboyant", meaning: "[형] 현란한, 화려한." },
  { word: "helpless", meaning: "[형] 무력한." },
  { word: "integral", meaning: "[형] 완전한; 필수의." },
  { word: "nostrum", meaning: "[명] 묘안, 묘책." },
  { word: "recourse", meaning: "[명] 의지, 의존." },
  { word: "sumptuous", meaning: "[형] 사치스러운." },
  { word: "vulgar", meaning: "[형] 저속한; 통속적인." },
  { word: "amplitude", meaning: "[명] 넓이, 폭." },
  { word: "benediction", meaning: "[명] 축사, 축복." },
  { word: "colossal", meaning: "[형] 거대한." },
  { word: "demobilize", meaning: "[동] 부대를 해산하다." },
  { word: "exalt", meaning: "[동] 높이다; 칭찬하다." },
  { word: "insinuate", meaning: "[동] 넌지시 말하다, 암시하다." },
  { word: "plank", meaning: "[명] 널빤지, 판자." },
  { word: "topple", meaning: "[동] 쓰러지다, 와해하다." },
  { word: "authority", meaning: "[명] 권위; 권한." },
  { word: "entry", meaning: "[명] 입장; 가입." },
  { word: "catastrophe", meaning: "[명] 대참사; 격변." },
  { word: "regardless", meaning: "[형] 무관심한; 신경 쓰지 않는." },
  { word: "credulous", meaning: "[형] 쉽사리 믿는." },
  { word: "imminent", meaning: "[형] 절박한, 급박한." },
  { word: "lantern", meaning: "[명] 등불, 랜턴." },
  { word: "overflow", meaning: "[동][명] 넘치다; 범람; 과잉." },
  { word: "rage", meaning: "[명][동] 격노; 격노하다." },
  { word: "sled", meaning: "[명] 썰매." },
  { word: "thrift", meaning: "[형] 검소한." },
  { word: "acquit", meaning: "[동] 석방하다, 무죄 방면하다." },
  { word: "avalanche", meaning: "[명] 눈사태." },
  { word: "canvas", meaning: "[명] 화포, 캔버스." },
  { word: "compliant", meaning: "[형] 고분고분한." },
  { word: "dearth", meaning: "[명] 부족, 결핍." },
  { word: "dispense", meaning: "[동] 분배하다; 면제하다." },
  { word: "engross", meaning: "[동] 몰두하게 하다." },
  { word: "furtive", meaning: "[형] 은밀한, 남모르게 하는." },
  { word: "improvident", meaning: "[형] 앞날을 생각하지 않는." },
  { word: "intervene", meaning: "[동] 개입하다; 중재하다." },
  { word: "mash", meaning: "[동] 짓이기다." },
  { word: "obsess", meaning: "[동] (귀신 등에) 사로잡히다." },
  { word: "petty", meaning: "[형] 사소한; 쩨쩨한." },
  { word: "query", meaning: "[명] 질문, 의문." },
  { word: "repel", meaning: "[동] 쫓아 버리다." },
  { word: "segment", meaning: "[명][동] 단편, 부분; 분할하다." },
  { word: "stew", meaning: "[동] 끓이다; 졸이다." },
  { word: "turmoil", meaning: "[명] 소란, 혼란." },
  { word: "wrench", meaning: "[동] 비틀다." },
  { word: "ascertain", meaning: "[동] 확인하다." },
  { word: "ankle", meaning: "[명] 발목." },
  { word: "communal", meaning: "[형] 공동의, 공유의." },
  { word: "dehydrate", meaning: "[동] 탈수하다." },
  { word: "edict", meaning: "[명] 포고; 명령." },
  { word: "flashlight", meaning: "[명] 섬광; 손전등." },
  { word: "herbivore", meaning: "[명] 초식동물." },
  { word: "interrelated", meaning: "[형] 서로 관계가 있는, 상관의." },
  { word: "nullify", meaning: "[동] 무효로 하다." },
  { word: "regiment", meaning: "[명] 연대; 무리." },
  { word: "tack", meaning: "[명] 압정." },
  { word: "warp", meaning: "[동] 뒤틀다; 뒤틀리다." },
  { word: "anti-social", meaning: "[형] 반사회적인; 비사교적인." },
  { word: "besiege", meaning: "[동] 포위하다, 에워싸다." },
  { word: "deliberate", meaning: "[동] 숙고하다." },
  { word: "denizen", meaning: "[명] 주민; 거주자." },
  { word: "exodus", meaning: "[명] 집단이동." },
  { word: "installment", meaning: "[명] 할부; 할부금." },
  { word: "plunder", meaning: "[동] 약탈하다." },
  { word: "tram", meaning: "[명] 전차." },
  { word: "privacy", meaning: "[명] 사생활." },
  { word: "edition", meaning: "[명] 판; 발행부수." },
  { word: "simultaneous", meaning: "[형] 동시의." },
  { word: "decipher", meaning: "[동] (암호 등을) 해독하다." },
  { word: "immoral", meaning: "[형] 부도덕한." },
  { word: "latitude", meaning: "[명] 위도." },
  { word: "overnight", meaning: "[형][부] 간밤의; 밤새도록." },
  { word: "ratify", meaning: "[동] 비준하다." },
  { word: "slot", meaning: "[명][동] 틈; 동전 등을 투입하다." },
  { word: "token", meaning: "[명] 징후; 특징." },
  { word: "adept", meaning: "[형][명] 숙달된; 숙련자, 달인." },
  { word: "averse", meaning: "[형] 혐오하는, 반대하는." },
  { word: "capitalism", meaning: "[명] 자본주의." },
  { word: "comply", meaning: "[동] 응낙하다, 동의하다." },
  { word: "decimate", meaning: "[동] 인구, 개체를 크게 줄이다." },
  { word: "disseminate", meaning: "[동] 퍼뜨리다, 유포시키다." },
  { word: "enroll", meaning: "[동] 등록하다." },
  { word: "gaiety", meaning: "[명] 유쾌, 명랑." },
  { word: "inadequate", meaning: "[형] 부적당한; 불충분한." },
  { word: "intestine", meaning: "[형][명] 내부의; (신체의) 장." },
  { word: "maternal", meaning: "[형] 어머니의, 모성의." },
  { word: "onset", meaning: "[명] 시작, 발단." },
  { word: "phantom", meaning: "[명] 유령; 환영." },
  { word: "racial", meaning: "[형] 인종의." },
  { word: "repetition", meaning: "[명] 반복, 되풀이." },
  { word: "self-control", meaning: "[명] 자제심; 극기." },
  { word: "stifle", meaning: "[동] 질식시키다." },
  { word: "ubiquitous", meaning: "[형] 어디에나 있는, 산재하는." },
  { word: "yawn", meaning: "[명][동] 하품; 하품하다." },
  { word: "atlas", meaning: "[명] 지도책." },
  { word: "capsize", meaning: "[동] 뒤집히다; 전복시키다." },
  { word: "communism", meaning: "[명] 공산주의." },
  { word: "deity", meaning: "[명] 신; 신성." },
  { word: "egocentric", meaning: "[형] 자기중심의, 이기적인." },
  { word: "flint", meaning: "[명] 부싯돌." },
  { word: "hoof", meaning: "[명] 발굽." },
  { word: "intersect", meaning: "[동] 가로지르다, 교차하다." },
  { word: "onward", meaning: "[부] 전방으로, 앞으로." },
  { word: "rehabilitate", meaning: "[동] 복원하다; 회복시키다." },
  { word: "tackle", meaning: "[명][동] 연장; (문제에) 달려들다." },
  { word: "withhold", meaning: "[동] 보류하다; 말리다." },
  { word: "apathetic", meaning: "[형] 냉담한, 무관심한." },
  { word: "binary", meaning: "[형] 2진법의; 이원의." },
  { word: "commonplace", meaning: "[형] 평범한." },
  { word: "deploy", meaning: "[동] (군대 등을) 배치하다." },
  { word: "fallout", meaning: "[명] 방사능 낙진." },
  { word: "instill", meaning: "[동] 주입시키다." },
  { word: "proxy", meaning: "[명] 대리; 대리인." },
  { word: "Trinity", meaning: "[명] 삼위일체." },
  { word: "historic", meaning: "[형] 역사적으로 유명한." },
  { word: "inland", meaning: "[형][부] 내륙의; 내륙으로." },
  { word: "stereotype", meaning: "[형][명] 판에 박힌; 상투적인 수단." },
  { word: "degrade", meaning: "[동] 격하시키다, 좌천시키다." },
  { word: "immutable", meaning: "[형] 바꿀 수 없는." },
  { word: "loom", meaning: "[동][명] 어렴풋이 보이다; 베틀." },
  { word: "pacify", meaning: "[동] 달래다, 진정시키다." },
  { word: "ravage", meaning: "[명][동] 파괴; 파괴하다." },
  { word: "sneak", meaning: "[동] 몰래 움직이다." },
  { word: "tow", meaning: "[동][명] 끌다, 견인하다; 견인." },
  { word: "adoption", meaning: "[명] 채택; 입양." },
  { word: "aviation", meaning: "[명] 비행, 항공." },
  { word: "caption", meaning: "[명] 표제; 자막." },
  { word: "compost", meaning: "[명] 혼합물, 퇴비." },
  { word: "decisive", meaning: "[형] 결정적인, 단호한." },
  { word: "dissuade", meaning: "[동] 단념시키다." },
  { word: "erudite", meaning: "[형] 박식한." },
  { word: "gateway", meaning: "[명] 문, 출입구." },
  { word: "incite", meaning: "[동] 자극하다; 유발하다." },
  { word: "intrepid", meaning: "[형] 용맹스러운." },
  { word: "maxim", meaning: "[명] 격언, 금언." },
  { word: "optical", meaning: "[형] 눈의; 시각의." },
  { word: "phonograph", meaning: "[명] 축음기." },
  { word: "rack", meaning: "[명] 선반; 걸이." },
  { word: "replenish", meaning: "[동] 채우다; 새로 보충하다." },
  { word: "animate", meaning: "[형] 활력 있는." },
  { word: "stimulus", meaning: "[명] 자극, 격려." },
  { word: "undermine", meaning: "[명] 밑을 파다; 손상시키다." },
  { word: "diploma", meaning: "[명] 학위 수여증." },
  { word: "aura", meaning: "[명] 묘한 분위기, 아우라." },
  { word: "cardiac", meaning: "[형] 심장의." },
  { word: "compatible", meaning: "[형] 양립할 수 있는; 조화되는." },
  { word: "demon", meaning: "[명] 악마, 귀신." },
  { word: "egoism", meaning: "[명] 이기주의." },
  { word: "fluorescent", meaning: "[형] 형광을 내는; 빛나는." },
  { word: "horoscope", meaning: "[명] 별점, 12궁도." },
  { word: "intimidate", meaning: "[동] 위협하다, 협박하다." },
  { word: "ordeal", meaning: "[명] 시련." },
  { word: "relic", meaning: "[명] 유물, 유적." },
  { word: "tactics", meaning: "[명] 전술." },
  { word: "foam", meaning: "[명][동] 거품, 거품이 일다." },
  { word: "apprentice", meaning: "[명] 도제, 실습생." },
  { word: "biochemical", meaning: "[명][형] 생화학 물질; 생화학의." },
  { word: "condolence", meaning: "[명] 애도." },
  { word: "derogatory", meaning: "[형] (명예 등을) 손상시키는." },
  { word: "ferocious", meaning: "[형] 사나운; 엄청난." },
  { word: "intangible", meaning: "[형] 만질 수 없는; 무형의." },
  { word: "puberty", meaning: "[명] 사춘기; 개화기." },
  { word: "ulcer", meaning: "[명] 궤양." },
  { word: "wire", meaning: "[명] 철사; 전선." },
  { word: "originate", meaning: "[동] 시작되다; 생기다." },
  { word: "miner", meaning: "[명] 광부." },
  { word: "successive", meaning: "[형] 연속적인; 잇따른." },
  { word: "dictation", meaning: "[명] 구술; 명령; 받아쓰기." },
  { word: "impair", meaning: "[동] 손상시키다, 해치다." },
  { word: "subject", meaning: "[동] 복종시키다." },
  { word: "paralysis", meaning: "[명] 마비." },
  { word: "reference", meaning: "[명] 문의; 참조; 언급." },
  { word: "sole", meaning: "[형] 유일한." },
  { word: "tractor", meaning: "[명] 트랙터; 견인차." },
  { word: "advocacy", meaning: "[명] 옹호, 지지." },
  { word: "badger", meaning: "[동][명] 조르다, 괴롭히다, 오소리." },
  { word: "cardinal", meaning: "[형][명] 기본적인; 중요한; 추기경." },
  { word: "comrade", meaning: "[명] 동료, 친구." },
  { word: "decode", meaning: "[동] 암호를 풀다, 해독하다." },
  { word: "distill", meaning: "[동] 증류하다." },
  { word: "genesis", meaning: "[명] 발생, 기원." },
  { word: "incompatible", meaning: "[형] 모순된; 양립할 수 없는." },
  { word: "intrigue", meaning: "[명][동] 음모; 음모를 꾸미다." },
  { word: "mediocre", meaning: "[형] 평범한; 보통의." },
  { word: "orient", meaning: "[명][동] 동양; 적응시키다." },
  { word: "pillar", meaning: "[명] 기둥." },
  { word: "raid", meaning: "[명] 공격, 습격." },
  { word: "repose", meaning: "[명][동] 휴식; 휴식을 취하다." },
  { word: "Senate", meaning: "[명] (미국의) 상원." },
  { word: "stringent", meaning: "[형] 절박한, 시급한." },
  { word: "underneath", meaning: "[전] ~의 아래에." },
  { word: "gifted", meaning: "[형] 타고난 재능이 있는." },
  { word: "avenge", meaning: "[동] 복수하다, 앙갚음하다." },
  { word: "carnivore", meaning: "[명] 육식동물." },
  { word: "complacent", meaning: "[형] 자기만족의." },
  { word: "denomination", meaning: "[명] 명칭; 액면가." },
  { word: "elapse", meaning: "[명][동] 시간의 경과; 경과하다." },
  { word: "footstep", meaning: "[명] 발자국; 발자국 소리." },
  { word: "hostage", meaning: "[명] 인질, 볼모." },
  { word: "inundate", meaning: "[동] 범람시키다." },
  { word: "outset", meaning: "[명] 착수; 시작." },
  { word: "rendezvous", meaning: "[명] 회합, 랑데부." },
  { word: "terrace", meaning: "[명] 발코니, 테라스." },
  { word: "magnanimous", meaning: "[형] 도량이 넓은, 관대한." },
  { word: "apprise", meaning: "[동] ~에게 통고하다." },
  { word: "alternate", meaning: "[형] 교대의." },
  { word: "conduit", meaning: "[명] 도관; 도랑." },
  { word: "diffusion", meaning: "[명] 전파; 확산." },
  { word: "fervent", meaning: "[형] 타는 듯한; 열렬한." },
  { word: "complicate", meaning: "[동] 복잡하게 하다." },
  { word: "unleash", meaning: "[동] 풀어 주다." },
  { word: "capable", meaning: "[형] 유능한; ~할 능력이 있는." },
  { word: "quote", meaning: "[동] 인용하다." },
  { word: "optional", meaning: "[형] 임의의; 선택의." },
  { word: "suspicion", meaning: "[명] 의심; 의혹." },
  { word: "erosion", meaning: "[명] 부식; 침식." },
  { word: "imperative", meaning: "[형] 명령의; 강제적인." },
  { word: "meditate", meaning: "[동] 명상하다." },
  { word: "passionate", meaning: "[형] 열정적인." },
  { word: "refined", meaning: "[형] 정제된." },
  { word: "sophomore", meaning: "[명] 2학년생." },
  { word: "transit", meaning: "[명][동] 통행; 통로; 횡단하다." },
  { word: "affirm", meaning: "[동] 확언하다; 긍정하다." },
  { word: "bait", meaning: "[명] 미끼; 꾀다." },
  { word: "carefree", meaning: "[형] 근심이 없는." },
  { word: "concise", meaning: "[형] 간결한, 간명한." },
  { word: "decree", meaning: "[명] 법령, 폭." },
  { word: "divert", meaning: "[동] 주의를 딴 데로 돌리다." },
  { word: "ethics", meaning: "[명] 윤리학." },
  { word: "glaze", meaning: "[동] 윤을 내다." },
  { word: "incomplete", meaning: "[형] 불완전한, 불충분한." },
  { word: "introvert", meaning: "[형] 내성적인." },
  { word: "meek", meaning: "[형] 온순한." },
  { word: "oscillate", meaning: "[동] 진동하다; 왕복하다." },
  { word: "pirate", meaning: "[명][동] 해적; 약탈하다; 표절하다." },
  { word: "rampart", meaning: "[명][동] 성벽; 방어하다." },
  { word: "reprimand", meaning: "[명][동] 질책; 비난; 꾸짖다." },
  { word: "sensor", meaning: "[명] 감지 장치." },
  { word: "stroll", meaning: "[동][명] 어슬렁거리다; 산책." },
  { word: "unilateral", meaning: "[형] 일방적인; 단독의." },
  { word: "aborigine", meaning: "[명] 원주민, 토착민." },
  { word: "avid", meaning: "[형] 탐욕스러운; 열심인." },
  { word: "cede", meaning: "[동] 양도하다, 인도하다." },
  { word: "complexity", meaning: "[명] 복잡성." },
  { word: "dent", meaning: "[명][동] 흠집; 손상시키다." },
  { word: "elegy", meaning: "[명] 애가, 비가." },
  { word: "forthcoming", meaning: "[형] 근간의; 다가오는." },
  { word: "hound", meaning: "[명] 사냥개." },
  { word: "invective", meaning: "[명][형] 독설; 독설의." },
  { word: "overtake", meaning: "[동] 따라잡다; 추월하다." },
  { word: "renown", meaning: "[명] 명성, 명망." },
  { word: "thermal", meaning: "[형] 열의; 뜨거운." },
  { word: "account for", meaning: "설명하다." },
  { word: "transport", meaning: "[동] 운송하다." },
  { word: "blot", meaning: "[명][동] 얼룩; 오명; 더럽히다." },
  { word: "conglomerate", meaning: "[명] 거대복합기업." },
  { word: "diminution", meaning: "[명] 감소, 축소." },
  { word: "feudal", meaning: "[형] 봉건제의." },
  { word: "kinetic", meaning: "[형] 운동의, 활동적인." },
  { word: "rehearsal", meaning: "[명] 연습; 시연." },
  { word: "abstract", meaning: "[명] 추상." },
  { word: "deceive", meaning: "[동] 속이다, 사기 치다." },
  { word: "rival", meaning: "[명][동] 경쟁자; 경쟁하다." },
  { word: "resistance", meaning: "[명] 저항; 반대." },
  { word: "temptation", meaning: "[명] 유혹." },
  { word: "erroneous", meaning: "[형] 잘못된, 틀린." },
  { word: "impetus", meaning: "[명] 추진력." },
  { word: "marital", meaning: "[형] 혼인의, 부부의." },
  { word: "patrol", meaning: "[명][동] 순찰; 순찰하다." },
  { word: "refute", meaning: "[동] 반박하다; 이의를 제기하다." },
  { word: "sovereign", meaning: "[명][형] 주권자; 주권국의." },
  { word: "transmission", meaning: "[명] 전송; 전도." },
  { word: "aide", meaning: "[명] 조력자, 보좌관." },
  { word: "barometer", meaning: "[명] 기압계; 척도." },
  { word: "cargo", meaning: "[명] 화물." },
  { word: "condemn", meaning: "[동] 비난하다." },
  { word: "deem", meaning: "[동] 여기다, 간주하다." },
  { word: "divulge", meaning: "[동] 누설하다." },
  { word: "excursion", meaning: "[명] 소풍." },
  { word: "incorporated", meaning: "[형] 법인조직의; 주식회사의." },
  { word: "intrude", meaning: "[동] 간섭하다; 끼어들다." },
  { word: "mellow", meaning: "[형] 달콤한; 감미로운." },
  { word: "outlaw", meaning: "[동] 불법화하다." },
  { word: "placate", meaning: "[동] 달래다, 화해시키다." },
  { word: "realm", meaning: "[명] 범위, 영역; ~계." },
  { word: "reprobate", meaning: "[동] 비난하다, 책망하다." },
  { word: "sheriff", meaning: "[명] 보안관." },
  { word: "subconscious", meaning: "[형] 잠재의식의." },
  { word: "unknown", meaning: "[형] 무명의; 미지의." },
  { word: "acclaim", meaning: "[명][동] 갈채; 갈채를 보내다." },
  { word: "avow", meaning: "[동] 공언하다." },
  { word: "celestial", meaning: "[형] 하늘의, 천상의." },
  { word: "congregate", meaning: "[동] 모이다; 모으다." },
  { word: "deputy", meaning: "[명][형] 대리인; 대리의; 부~." },
  { word: "embed", meaning: "[동] 끼워 넣다; 박아 넣다." },
  { word: "fortitude", meaning: "[명] 용기, 강인성." },
  { word: "housekeeping", meaning: "[명] 가사, 살림." },
  { word: "involuntary", meaning: "[형] 무의식중의." },
  { word: "overture", meaning: "[명] 서곡; 제안." },
  { word: "repent", meaning: "[동] 후회하다." },
  { word: "thrash", meaning: "[동] (회초리 등으로) 때리다." },
  { word: "discount", meaning: "[동] 할인하다." },
  { word: "artillery", meaning: "[명] 포, 대포." },
  { word: "blotch", meaning: "[명] 부스럼; 검버섯." },
  { word: "construe", meaning: "[동] 해석하다; 추론하다." },
  { word: "discontent", meaning: "[명][형] 불만; 불만의." },
  { word: "fission", meaning: "[명] 분열; 핵분열." },
  { word: "laggard", meaning: "[명] 느림보." },
  { word: "rein", meaning: "[명] 고삐; 구속." },
  { word: "aquatic", meaning: "[형] 수생의; 물의." },
  { word: "departure", meaning: "[명] 출발, 떠남." },
  { word: "accommodate", meaning: "[동] 수용하다, 숙박시키다." },
  { word: "robbery", meaning: "[명] 강도, 약탈." },
  { word: "unity", meaning: "[명] 통일; 통일성." },
  { word: "exemplary", meaning: "[형] 모범적인." },
  { word: "incense", meaning: "[명] 향, 향내." },
  { word: "maze", meaning: "[명] 미로, 미궁." },
  { word: "periodical", meaning: "[형][명] 주기적인; 정기간행물." },
  { word: "regime", meaning: "[명] 정권, 정부." },
  { word: "spacious", meaning: "[형] 넓은; 광범위한." },
  { word: "trespass", meaning: "[동] 침해하다; 침입하다." },
  { word: "blond", meaning: "[형] 금발의." },
  { word: "bulb", meaning: "[명] 전구; 구근." },
  { word: "caste", meaning: "[명] 카스트, 특권계급." },
  { word: "confiscate", meaning: "[동] 몰수하다, 압수하다." },
  { word: "defendant", meaning: "[명][형] 피고; 피고의." },
  { word: "doze", meaning: "[동] 졸다." },
  { word: "exemplify", meaning: "[동] 예시하다." },
  { word: "grudge", meaning: "[동][명] 투덜대다; 악의, 원한." },
  { word: "indict", meaning: "[동] 기소하다; 고발하다." },
  { word: "invalid", meaning: "[명] 환자." },
  { word: "milestone", meaning: "[명] 이정표." },
  { word: "output", meaning: "[명] 산출; 결과물." },
  { word: "placid", meaning: "[형] 평온한; 조용한." },
  { word: "rebuff", meaning: "[동][명] 거절하다; 퇴짜." },
  { word: "reptile", meaning: "[명] 파충류." },
  { word: "siege", meaning: "[명][동] 포위, 포위하다." },
  { word: "succinct", meaning: "[형] 간결한." },
  { word: "unlock", meaning: "[동] 자물쇠를 열다." },
  { word: "activate", meaning: "[동] 활성화하다." },
  { word: "baffle", meaning: "[동] 당황케 하다, 좌절시키다." },
  { word: "centennial", meaning: "[형] 100년마다의." },
  { word: "conspiracy", meaning: "[명] 음모, 모의." },
  { word: "despicable", meaning: "[형] 야비한, 비열한." },
  { word: "emblem", meaning: "[명] 상징." },
  { word: "fraudulent", meaning: "[형] 부정한; 속이는." },
  { word: "humane", meaning: "[형] 자비로운, 인도적인." },
  { word: "irreversible", meaning: "[형] 뒤집을 수 없는." },
  { word: "paltry", meaning: "[형] 하찮은, 무가치한." },
  { word: "replica", meaning: "[명] 복사; 모사." },
  { word: "throng", meaning: "[명] 군중, 혼잡." },
  { word: "abet", meaning: "[동] 선동하다, 부추기다." },
  { word: "artisan", meaning: "[명] 숙련공." },
  { word: "bondage", meaning: "[동] 노예 신분; 속박." },
  { word: "cornerstone", meaning: "[명] 초석, 토대." },
  { word: "disobedience", meaning: "[명] 불복종." },
  { word: "fissure", meaning: "[명] 갈라진 틈, 균열." },
  { word: "lash", meaning: "[명] 채찍질; 태형." },
  { word: "repertory", meaning: "[명] 축적; 저장소." },
  { word: "attribute", meaning: "[명] 특질." },
  { word: "participant", meaning: "[형][명] 참여하는; 참가자." },
  { word: "rectangle", meaning: "[명] 직사각형." },
  { word: "sociable", meaning: "[형] 사교적인." },
  { word: "foul", meaning: "[형][명] 부정한, 반칙의; 반칙." },
  { word: "forge", meaning: "[동][명] 위조하다; 대장간." },
  { word: "indignant", meaning: "[형] 화난; 성난." },
  { word: "meadow", meaning: "[명] 풀밭, 목초지." },
  { word: "perplex", meaning: "[동] 당황하게 만들다." },
  { word: "relay", meaning: "[명] (방송) 중계." },
  { word: "splash", meaning: "[동] (물 등을) 튀기다." },
  { word: "underlying", meaning: "[형] 기저의; 근원적인." },
  { word: "allege", meaning: "[동] 단언하다, 주장하다." },
  { word: "benign", meaning: "[형] 친절한, 온화한." },
  { word: "castigate", meaning: "[동][명] 징계하다; 징계; 혹평." },
  { word: "deficiency", meaning: "[명] 결핍, 부족." },
  { word: "drawback", meaning: "[명] 결점; 장애." },
  { word: "expertise", meaning: "[명] 전문성; 전문지식." },
  { word: "gutter", meaning: "[명] 하수도, 도랑." },
  { word: "indigenous", meaning: "[형] 토착의; 타고난." },
  { word: "invaluable", meaning: "[형] 매우 귀중한." },
  { word: "missionary", meaning: "[형][명] 전도의; 전도사." },
  { word: "overlap", meaning: "[명][동] 중첩, 오버랩; 겹치다." },
  { word: "plight", meaning: "[명] 곤경, 곤란." },
  { word: "recant", meaning: "[동] 취소하다, 철회하다." },
  { word: "repulse", meaning: "[동] 격퇴하다; 거절하다." },
  { word: "sift", meaning: "[동] 체로 치다; 가려내다." },
  { word: "succumb", meaning: "[동] 굴복하다." },
  { word: "update", meaning: "[동][명] 최신으로 만들다, 업데이트." },
  { word: "addictive", meaning: "[형] 중독성의." },
  { word: "banish", meaning: "[동] 추방하다." },
  { word: "certify", meaning: "[동] 증명하다; 공인하다." },
  { word: "constrain", meaning: "[동] 강요하다, 속박하다." },
  { word: "detain", meaning: "[동] 붙들다; 억류하다." },
  { word: "empathy", meaning: "[명] 감정 이입." },
  { word: "freelance", meaning: "[형] 자유계약의; 전속이 아닌." },
  { word: "hunch", meaning: "[명] 혹; 군살." },
  { word: "itinerary", meaning: "[명] 여정, 여행 일정." },
  { word: "paramount", meaning: "[형] 최고의; 탁월한." },
  { word: "revert", meaning: "[동] 되돌아가다; 복귀하다." },
  { word: "thwart", meaning: "[동] 훼방 놓다." },
  { word: "ablaze", meaning: "[형][부] 화염에 휩싸인; 흥분하여." },
  { word: "assay", meaning: "[동] 분석하다; 평가하다." },
  { word: "bribery", meaning: "[명] 뇌물." },
  { word: "cremate", meaning: "[명][동] 화장; 소각하다." },
  { word: "disprove", meaning: "[동] 반박하다; 반증하다." },
  { word: "flake", meaning: "[명] 얇은 조각, 플레이크." },
  { word: "lawsuit", meaning: "[명] 소송." },
  { word: "reverberate", meaning: "[동] 반향하다; 반사하다." },
  { word: "payback", meaning: "[명][형] 환불; 상환; 환불의." },
  { word: "regulation", meaning: "[명] 규정, 규칙." },
  { word: "unlimited", meaning: "[형] 무제한의." },
  { word: "vegetarian", meaning: "[형][명] 채식의; 채식주의자." },
  { word: "nonetheless", meaning: "[부] 그럼에도 불구하고." },
  { word: "fortress", meaning: "[명] 요새, 성채." },
  { word: "indulge", meaning: "[동] 만족시키다; 탐닉하다." },
  { word: "mandatory", meaning: "[형] 위임의; 의무의; 명령의." },
  { word: "persistent", meaning: "[형] 고집하는; 완고한." },
  { word: "remnant", meaning: "[명] 나머지; 찌꺼기." },
  { word: "spouse", meaning: "[명] 배우자." },
  { word: "utensil", meaning: "[명] 부엌용품." },
  { word: "allegory", meaning: "[명] 우화, 비유담." },
  { word: "bereave", meaning: "[동] 빼앗다." },
  { word: "cater", meaning: "[동] 조달하다; 요구에 응하다." },
  { word: "consecutive", meaning: "[형] 연속적인, 잇따른." },
  { word: "degenerate", meaning: "[동] 퇴보하다; 타락하다." },
  { word: "drench", meaning: "[동] 흠뻑 적시다." },
  { word: "exterior", meaning: "[형] 외부의, 바깥쪽의." },
  { word: "habitual", meaning: "[형] 습관적인." },
  { word: "indulgent", meaning: "[형] 방임하는; 관대한." },
  { word: "invoice", meaning: "[명] 송장." },
  { word: "mistress", meaning: "[명] 여주인; 여성 대가." },
  { word: "overthrow", meaning: "[동] 전복하다; 뒤엎다." },
  { word: "polio", meaning: "[명] 소아마비." },
  { word: "reception", meaning: "[명] 환영회; 수령." },
  { word: "skeptic", meaning: "[명] 회의론자." },
  { word: "suffrage", meaning: "[명] 투표; 투표권." },
  { word: "usher", meaning: "[명] 안내인." },
  { word: "minute", meaning: "[형] 미세한; 상세한." },
  { word: "bankruptcy", meaning: "[명] 파산." },
  { word: "chaotic", meaning: "[형] 혼돈의." },
  { word: "contestant", meaning: "[명] 경쟁자, 논쟁자." },
  { word: "detour", meaning: "[명][동] 우회; 우회하다." },
  { word: "breathtaking", meaning: "[형] 숨 막히는." },
  { word: "fringe", meaning: "[명] 술 장식; 가장자리." },
  { word: "hybrid", meaning: "[명] 잡종, 혼성물." },
  { word: "jubilant", meaning: "[형] 환호하는." },
  { word: "patronize", meaning: "[동] 후원하다." },
  { word: "sage", meaning: "[형][명] 슬기로운, 현명한; 현인." },
  { word: "tinker", meaning: "[명] 땜장이; 서툰 수선." },
  { word: "abreast", meaning: "[부] 나란히, 병렬하여." },
  { word: "assort", meaning: "[동] 분류하다." },
  { word: "breast", meaning: "[명] 가슴." },
  { word: "crest", meaning: "[동] (새의) 볏, 꼭대기." },
  { word: "diurnal", meaning: "[형] 주간의." },
  { word: "furnace", meaning: "[명] 노; 화덕." },
  { word: "loot", meaning: "[동][명] 약탈하다; 약탈품." },
  { word: "rhapsody", meaning: "[명] 광시곡; 열정적인 말." },
  { word: "penniless", meaning: "[형] 무일푼의." },
  { word: "awkward", meaning: "[형] 어색한, 불편한." },
  { word: "accelerate", meaning: "[동] 가속하다." },
  { word: "vow", meaning: "[명][동] 맹세; 맹세하다." },
  { word: "apparatus", meaning: "[명] 장치, 기구." },
  { word: "gallant", meaning: "[형][명] 씩씩한, 호남의; 호남." },
  { word: "meticulous", meaning: "[형] 소심한; 신중한." },
  { word: "pertinent", meaning: "[형] 타당한, 적절한." },
  { word: "reprove", meaning: "[동] 꾸짖다; 훈계하다." },
  { word: "spurious", meaning: "[형] 가짜의, 그럴듯한." },
  { word: "versatile", meaning: "[형] 재주가 많은; 다방면의." },
  { word: "alleviate", meaning: "[동] 누그러뜨리다, 완화시키다." },
  { word: "biblical", meaning: "[형] 성경의." },
  { word: "consign", meaning: "[동] 인도하다; 위탁하다." },
  { word: "delete", meaning: "[동] 삭제하다." },
  { word: "drizzle", meaning: "[명] 이슬비." },
  { word: "extricate", meaning: "[동] 구출하다; 식별하다." },
  { word: "haven", meaning: "[명] 피난처." },
  { word: "inefficient", meaning: "[형] 효과 없는; 무능한." },
  { word: "journalism", meaning: "[명] 저널리즘; 언론." },
  { word: "mobility", meaning: "[명] 이동성; 기동성." },
  { word: "packet", meaning: "[명] 한 묶음." },
  { word: "pollen", meaning: "[명] 꽃가루, 화분." },
  { word: "recess", meaning: "[명][동] 휴회; 휴회하다." },
  { word: "resilient", meaning: "[형] 탄력 있는; 쾌활한." },
  { word: "skinny", meaning: "[형] 여윈; 인색한." },
  { word: "superb", meaning: "[형] 훌륭한; 빼어난." },
  { word: "vaccinate", meaning: "[동] 예방접종을 하다." },
  { word: "affront", meaning: "[명][동] 무례, 모욕; 모욕하다." },
  { word: "barbarian", meaning: "[명] 야만인, 미개인." },
  { word: "charismatic", meaning: "[형] 카리스마적인." },
  { word: "contour", meaning: "[명] 윤곽." },
  { word: "diagonal", meaning: "[명][형] 대각선; 대각선의." },
  { word: "entangle", meaning: "[동] 얽히게 하다." },
  { word: "compulsive", meaning: "[형] 강박적인; 강제적인." },
  { word: "ideology", meaning: "[명] 이념, 이데올로기." },
  { word: "jug", meaning: "[명] 주전자." },
  { word: "pendulum", meaning: "[명] 흔들리는 추, 진자." },
  { word: "salvage", meaning: "[명][동] 해난구조; 구조하다." },
  { word: "tint", meaning: "[명][동] 엷은 빛깔; 채색하다." },
  { word: "contract", meaning: "[동] 계약하다." },
  { word: "asteroid", meaning: "[명] 소행성." },
  { word: "contrast", meaning: "[명] 대조." },
  { word: "crib", meaning: "[명] 구유, 여물통." },
  { word: "diversify", meaning: "[동] 다양화하다." },
  { word: "consummate", meaning: "[형] 완성된." },
  { word: "martyr", meaning: "[명] 순교자." },
  { word: "ripple", meaning: "[명] 잔물결, 파문." },
  { word: "royalty", meaning: "[명] 왕권, 위엄." },
  { word: "architect", meaning: "[명] 건축가." },
  { word: "aptitude", meaning: "[명] 적성, 소질." },
  { word: "affair", meaning: "[명] 일, 업무." },
  { word: "masterpiece", meaning: "[명] 걸작." },
  { word: "gathering", meaning: "[명] 모임." },
  { word: "inhibit", meaning: "[동] 금하다." },
  { word: "miniature", meaning: "[명][형] 모형; 소품; 소형의." },
  { word: "pierce", meaning: "[동] 꿰뚫다, 관통하다." },
  { word: "repudiate", meaning: "[동] 거부하다; 의절하다." },
  { word: "stack", meaning: "[명] 더미, 퇴적." },
  { word: "vinegar", meaning: "[명] 식초." },
  { word: "alliance", meaning: "[명] 동맹, 결연, 협력." },
  { word: "bilingual", meaning: "[형] 2개 국어를 하는." },
  { word: "chime", meaning: "[명][동] 종, 차임; 종을 울리다." },
  { word: "constituent", meaning: "[형][명] 구성하는; 요소; 유권자." },
  { word: "deleterious", meaning: "[형] 해로운, 유독한." },
  { word: "drowsy", meaning: "[형] 졸리는." },
  { word: "exuberant", meaning: "[형] 활력이 넘치는." },
  { word: "havoc", meaning: "[명] 대혼란." },
  { word: "inept", meaning: "[형] 부적당한, 서툰." },
  { word: "judicious", meaning: "[형] 현명한, 분별력 있는." },
  { word: "modernize", meaning: "[동] 현대화하다." },
  { word: "paddle", meaning: "[명][동] 노; 노를 젓다." },
  { word: "porcelain", meaning: "[명] 자기; 자기 제품." },
  { word: "recipient", meaning: "[형] 수용하는; 수령인." },
  { word: "restrain", meaning: "[동] 제지하다; 억제하다." },
  { word: "skull", meaning: "[명] 두개골." },
  { word: "swap", meaning: "[동] 교환하다; 맞바꾸다." },
  { word: "vacillate", meaning: "[동] 망설이다, 머뭇거리다." },
  { word: "akin", meaning: "[형] 동족의; 유사한." },
  { word: "baroque", meaning: "[형] 기이한, 바로크식의." },
  { word: "infamous", meaning: "[동] 수치스러운." },
  { word: "copious", meaning: "[형] 풍부한." },
  { word: "dire", meaning: "[형] 무서운; 긴박한." },
  { word: "entity", meaning: "[명] 실체, 본질." },
  { word: "gale", meaning: "[명] 질풍, 강풍." },
  { word: "illiterate", meaning: "[형] 문맹의, 무식한." },
  { word: "juggle", meaning: "[동] 요술을 부리다." },
  { word: "percussion", meaning: "[명] 충격; 진동; 타악기 연주." },
  { word: "sergeant", meaning: "[명] 하사관." },
  { word: "transcend", meaning: "[동] 초월하다." },
  { word: "acoustic", meaning: "[형] 청각의." },
  { word: "astrology", meaning: "[명] 점성술." },
  { word: "close", meaning: "[형] 가까운." },
  { word: "crisp", meaning: "[형] 부서지기 쉬운; 바삭바삭한." },
  { word: "doctoral", meaning: "[형] 박사의." },
  { word: "genealogy", meaning: "[명] 가계; 혈통." },
  { word: "mural", meaning: "[형][명] 벽의; 벽화." },
  { word: "rove", meaning: "[동] 헤매다, 떠돌다." },
  { word: "zoology", meaning: "[명] 동물학." },
];