const quizData = [
  { expression: "be going to", meaning: "~할 예정이다, ~할 것 같다" },
  { expression: "have to", meaning: "~해야 한다, ~하지 않으면 안된다" },
  { expression: "look at", meaning: "보다, 바라보다" },
  { expression: "think about (of)", meaning: "~에 대해 생각하다, 숙고하다" },
  { expression: "want to", meaning: "~하고 싶다" },
  { expression: "be interested in", meaning: "~에 관심이 있다, 흥미가 있다" },
  { expression: "a little", meaning: "조금(의), 소량(의)" },
  { expression: "a lot of (lots of)", meaning: "많은" },
  { expression: "one of", meaning: "~중의 하나" },
  { expression: "There be", meaning: "~이 있다" },
  { expression: "enjoy", meaning: "~하는 것을 즐기다" },
  { expression: "listen to", meaning: "~에 귀를 기울이다, 경청하다" },
  { expression: "talk about (of)", meaning: "~에 관해 말하다, 이야기하다" },
  { expression: "try to", meaning: "~하려고 노력하다" },
  { expression: "would like(love) to", meaning: "~하고 싶다" },
  { expression: "be good for", meaning: "~에 유익하다, ~에 적합하다" },
  { expression: "a lot", meaning: "매우, (비교급 앞에서) 훨씬, 많은 것" },
  { expression: "every day", meaning: "매일" },
  { expression: "to(in order to)", meaning: "~하기 위하여(목적)" },
  { expression: "get up", meaning: "일어나다" },
  { expression: "go ~ing", meaning: "~하러 가다" },
  { expression: "look for", meaning: "찾다" },
  { expression: "look like", meaning: "~처럼 보이다, ~인(일)것 같다" },
  { expression: "talk to", meaning: "~와 이야기하다, ~에게 말을 걸다" },
  { expression: "be(feel) proud of", meaning: "~을 자랑스럽게 여기다" },
  { expression: "for example", meaning: "예를 들면" },
  { expression: "of course", meaning: "물론" },
  { expression: "one day", meaning: "(과거 또는 미래의) 어느날" },
  { expression: "감정 형용사+to", meaning: "~해서, ~하니(원인)" },
  { expression: "come back (to)", meaning: "(~로) 돌아오다" },
  { expression: "need to", meaning: "~할 필요가 있다" },
  { expression: "pick up", meaning: "집다(줍다), 차에 태우다, (정보 등을) 얻다" },
  { expression: "take care of", meaning: "돌보다" },
  { expression: "wait for", meaning: "기다리다" },
  { expression: "be from", meaning: "~ 출신이다" },
  { expression: "at school", meaning: "학교에서, 수업 중에" },
  { expression: "in the future", meaning: "미래에, 앞으로" },
  { expression: "some of", meaning: "~중의 일부" },
  { expression: "enough to", meaning: "~할 만큼 충분히" },
  { expression: "go to bed", meaning: "잠자리에 들다" },
  { expression: "hear about (of)", meaning: "~에 대해 전해듣다, ~의 소식(소문)을 듣다" },
  { expression: "make friends (with)", meaning: "(~와) 친해지다, 사귀다" },
  { expression: "take A to B", meaning: "A를 B로 가져가다(데려가다)" },
  { expression: "thank A for B", meaning: "A에게 B에 대해 감사하다" },
  { expression: "be able to", meaning: "~할 수 있다" },
  { expression: "a few", meaning: "조금(의), 소수(몇몇)의" },
  { expression: "by the way", meaning: "그런데" },
  { expression: "in the morning/afternoon/evening", meaning: "아침/오후/저녁에" },
  { expression: "too ~ to", meaning: "너무 ~해서 ~할수 없다, (~하기에는 너무 ~하다)" },
  { expression: "come from", meaning: "~의 출신이다, ~에서 (나)오다, ~에서 유래하다, ~에서 생기다" },
  { expression: "go out", meaning: "밖으로 나가다, 외출하다" },
  { expression: "grow up", meaning: "어른이 되다, 성장하다" },
  { expression: "keep (on) ~ing", meaning: "계속 ~하다, 줄곧 ~하다" },
  { expression: "take off", meaning: "(옷 따위를) 벗다, 이륙하다" },
  { expression: "be good at", meaning: "~에 능숙하다, 잘하다" },
  { expression: "at night", meaning: "밤에" },
  { expression: "from A to B", meaning: "A에서(부터) B까지" },
  { expression: "in front of", meaning: "~의 앞에" },
  { expression: "to", meaning: "~하는 것(주어. 보어 기능)" },
  { expression: "come on", meaning: "자,, 빨리, 제발,, 기운을 내" },
  { expression: "decide to", meaning: "~하기로 결심(결정)하다" },
  { expression: "do(try) one's best", meaning: "최선을 다하다" },
  { expression: "get to", meaning: "~에 도착하다, ~하게 되다" },
  { expression: "used to", meaning: "(과거에) ~하곤 했다(이었다)" },
  { expression: "be full of", meaning: "~로 가득 차다" },
  { expression: "How(What) about ~ing?", meaning: "~은 어때?" },
  { expression: "next/this/last time", meaning: "다음번/이번/지난번에" },
  { expression: "over there/here", meaning: "저기/여기에, 저쪽/이쪽에" },
  { expression: "It be ~ (for A) to", meaning: "(A가) ~하는 것은 ~이다" },
  { expression: "come in", meaning: "(안으로) 들어가다(오다), 시작하다" },
  { expression: "don't have to", meaning: "~할 필요가 없다" },
  { expression: "keep a diary", meaning: "(습관적으로) 일기를 쓰다" },
  { expression: "put A into B", meaning: "A를 B안에 넣다, A를 B로 옮기다(번역하다)" },
  { expression: "stop ~ing", meaning: "~하는 것을 멈추다" },
  { expression: "be different from", meaning: "~와 다르다" },
  { expression: "more than", meaning: "~이상, ~보다 많은" },
  { expression: "most of", meaning: "대부분의" },
  { expression: "these days", meaning: "요즘" },
  { expression: "It be 성질형용사 of A to", meaning: "A가 ~하는 것은 ~이다" },
  { expression: "bring A to B", meaning: "A를 B로 가져오다(데려오다)" },
  { expression: "do one's homework", meaning: "숙제를 하다" },
  { expression: "go back (to)", meaning: "(~로) 돌아가다" },
  { expression: "help A with B", meaning: "A가 B하는 것을 돕다" },
  { expression: "sit down", meaning: "앉다" },
  { expression: "be worried about", meaning: "~에 대해 걱정하다" },
  { expression: "all of", meaning: "~중의 모두, 모든" },
  { expression: "between A and B", meaning: "A와 B 사이에" },
  { expression: "more and more", meaning: "점점 더, 더욱 더 많은" },
  { expression: "타동사 + to", meaning: "~하는 것을 ~하다(목적어 기능)" },
  { expression: "arrive at(in)", meaning: "~에 도착하다" },
  { expression: "go up", meaning: "오르다, 올라가다" },
  { expression: "have fun", meaning: "재미있게 놀다" },
  { expression: "help oneself (to)", meaning: "마음껏 먹다" },
  { expression: "put on", meaning: "(옷 등을) 입다, (연극 등을) 공연하다" },
  { expression: "be(get) ready to(for)", meaning: "~할 준비가 되다, 곧 ~할 수 있다(할 것 같다), 기꺼이 ~하다" },
  { expression: "at home", meaning: "집에서, 본국에서" },
  { expression: "at last", meaning: "마침내, 드디어" },
  { expression: "on one's(the) way (to)", meaning: "(로 가는) 도중에" },
  { expression: "how/what/where/when+to", meaning: "어떻게/무엇을/어디에서/언제 ~인지" },
  { expression: "belong to", meaning: "~에 속하다" },
  { expression: "say good-bye (to)", meaning: "(~에게) 작별인사를 하다" },
  { expression: "seem to", meaning: "~인 것 같다" },
  { expression: "take a picture (of)", meaning: "(~의) 사진을 찍다" },
  { expression: "would rather A (than B)", meaning: "(B하느니) 차라리 A하고 싶다, (B보다) A 하는게 낫다" },
  { expression: "be late for", meaning: "~에 늦다, ~에 지각하다" },
  { expression: "all over the world", meaning: "전 세계(에)" },
  { expression: "right away", meaning: "곧, 즉시" },
  { expression: "the next day", meaning: "그 다음날" },
  { expression: "명사 + to", meaning: "~할(하는) ~(명사를 꾸며주는 형용사 기능)" },
  { expression: "go to the movies", meaning: "영화 보러 가다" },
  { expression: "run away", meaning: "도망가다, 달아나다" },
  { expression: "take part in", meaning: "~에 참가하다" },
  { expression: "take out", meaning: "꺼내다, 대출(인출)하다, (음식을) 싸 갖고 가다" },
  { expression: "throw away", meaning: "내던지다, 버리다" },
  { expression: "be afraid of(that)", meaning: "~을 두려워하다" },
  { expression: "all day (long)", meaning: "하루종일" },
  { expression: "(a) part of", meaning: "~의 일부" },
  { expression: "A such as B (such A as B)", meaning: "B와 같은 A" },
  { expression: "동사 + ~ing", meaning: "~하는 것(주어. 보어 기능)" },
  { expression: "get on", meaning: "(탈것에) 타다" },
  { expression: "get together", meaning: "모이다" },
  { expression: "go on", meaning: "계속되다, 계속해서 ~하다" },
  { expression: "say hello to", meaning: "~에게 안부를 전하다, ~에게 인사하다" },
  { expression: "stand up", meaning: "일어서다" },
  { expression: "be famous for", meaning: "~로 유명하다" },
  { expression: "at that time", meaning: "그 때, 그 당시에" },
  { expression: "in fact", meaning: "사실상, 실제로" },
  { expression: "in my opinion", meaning: "내 의견으로는" },
  { expression: "타동사 + 동사~ing", meaning: "~하는 것을 ~하다(목적어기능)" },
  { expression: "have a good time", meaning: "즐겁게 지내다" },
  { expression: "make a noise", meaning: "소리를 내다, 떠들다" },
  { expression: "pay for", meaning: "~의 값을 치르다, 지불하다" },
  { expression: "turn on", meaning: "(전등,TV 등을) 켜다, (수도, 가스 등을) 틀다" },
  { expression: "write down", meaning: "적어놓다" },
  { expression: "be covered with", meaning: "~로 덮여 있다" },
  { expression: "around the world", meaning: "전 세계에" },
  { expression: "at first", meaning: "처음에" },
  { expression: "because of", meaning: "~때문에" },
  { expression: "be 동사~ing", meaning: "~하고 있는 중이다(진행형)" },
  { expression: "find out", meaning: "찾아내다, 알아내다" },
  { expression: "give up", meaning: "포기(단념)하다, 그만두다" },
  { expression: "look forward to 동사~ing", meaning: "~하기를 고대하다" },
  { expression: "wake up", meaning: "깨어나다, 깨우다" },
  { expression: "write (to)", meaning: "~에게 편지를 쓰다" },
  { expression: "be(feel) sorry for (to 동사, that절)", meaning: "유감스럽다, 안됐다, 미안하다" },
  { expression: "after school", meaning: "방과 후에" },
  { expression: "last night", meaning: "어젯밤에" },
  { expression: "right now", meaning: "지금 바로(당장)" },
  { expression: "be+과거분사(+by 행위자)", meaning: "(~에 의해) ~되다, (~지다,,~받다,,~당하다)(수동태)" },
  { expression: "come into", meaning: "~안에 들어오다" },
  { expression: "had better", meaning: "~하는 게 낫다" },
  { expression: "make it", meaning: "시간에 대다, 해내다, (서로) 만나기로 하다" },
  { expression: "take a walk", meaning: "산책하다" },
  { expression: "try on", meaning: "(옷 등을) 입어 보다" },
  { expression: "be made of", meaning: "~로 만들어지다" },
  { expression: "at once", meaning: "곧(즉시), 한꺼번에(동시에)" },
  { expression: "for a long time", meaning: "오랫동안" },
  { expression: "next to", meaning: "~옆에" },
  { expression: "be being+과거분사", meaning: "~되고 있는 중이다,(진행형 수동태)" },
  { expression: "come true", meaning: "실현되다, 사실이 되다" },
  { expression: "get a good/poor(bad) grade (in)", meaning: "(~에서) 좋은/나쁜 점수를 받다" },
  { expression: "go away", meaning: "가버리다, 떠나다, 사라지다" },
  { expression: "make a mistake (in)", meaning: "(~에서) 실수하다" },
  { expression: "smile at", meaning: "~에게 미소 짓다" },
  { expression: "be about to", meaning: "막 ~하려고 하다" },
  { expression: "by bus/car/subway", meaning: "버스/차/지하철을 타고" },
  { expression: "many/all kinds of", meaning: "많은/모든 종류의" },
  { expression: "thanks to", meaning: "~덕택에, ~때문에" },
  { expression: "have+과거분사", meaning: "과거부터 현재까지 동작,,상태의 계속,,경험,,완료(현재완료형)" },
  { expression: "come over", meaning: "집을 방문하다, (외국에서) 이주해오다" },
  { expression: "dream about(of)", meaning: "~에 대해 꿈꾸다" },
  { expression: "hear from", meaning: "~로부터 연락(편지,,전화,,전갈)을 받다" },
  { expression: "hope to", meaning: "~하기를 바라다(희망하다)" },
  { expression: "welcome to", meaning: "~에 온 것을 환영하다" },
  { expression: "be tired of", meaning: "~에 싫증이 나다" },
  { expression: "and so on(forth)", meaning: "기타 등등" },
  { expression: "on television(TV)", meaning: "텔레비전으로" },
  { expression: "on time", meaning: "시간을 어기지 않고, 제시간에" },
  { expression: "have been 동사~ing", meaning: "계속 ~해오고 있는 중이다(완료 진행형)" },
  { expression: "cheer up", meaning: "기운이 나다, 기운을 북돋우다" },
  { expression: "come out of", meaning: "~에서 밖으로 나오다" },
  { expression: "go by", meaning: "(사람,,시간,,기회 등이) 지나가다" },
  { expression: "stop by", meaning: "잠시 들르다" },
  { expression: "take a bus/taxi/subway", meaning: "버스/택시/지하철을 타다" },
  { expression: "be happy with", meaning: "~로 행복하다(기쁘다), ~에 만족하다" },
  { expression: "generally speaking", meaning: "일반적으로 말하면" },
  { expression: "some day(someday)", meaning: "(미래의) 언젠가, 훗날" },
  { expression: "this/that day", meaning: "이런/그런 식으로, 이쪽/저쪽으로" },
  { expression: "have been+과거분사", meaning: "~되어 왔다, ~된 적이 있다, ~되었다(완료 수동태)" },
  { expression: "get along (with)", meaning: "(~와) 잘 지내다" },
  { expression: "happen to 명사/동사", meaning: "~에게 일어나다/우연히 ~하다" },
  { expression: "make sense", meaning: "이치에 맞다, 일리가 있다," },
  { expression: "say(talk) to oneself", meaning: "혼잣말을 하다, 마음속으로 생각하다" },
  { expression: "turn off", meaning: "(전등,,TV 등을) 끄다, (수도,,가스 등을) 잠그다" },
  { expression: "be supposed to 동사", meaning: "~하기로 되어 있다,(예정,,의무)" },
  { expression: "all the time", meaning: "언제나, 항상" },
  { expression: "for a while", meaning: "잠시 동안" },
  { expression: "millions of", meaning: "수백만의, 무수한" },
  { expression: "had+과거분사", meaning: "과거 어느 시점까지 동작,,상태의 계속,,경험,,완료(과거완료), 과거 어느 시점보다 앞선 때" },
  { expression: "catch(get)/have a cold", meaning: "감기에 걸리다/걸려 있다" },
  { expression: "dress up", meaning: "잘 차려 입다, 정장하다, 분장하다" },
  { expression: "go straight", meaning: "곧장 가다" },
  { expression: "look around", meaning: "주위를 둘러보다" },
  { expression: "set up", meaning: "세우다, 설립(설치)하다" },
  { expression: "be used for", meaning: "~로(~을 위해) 사용되다" },
  { expression: "a piece of", meaning: "한 조각의, 한 개의" },
  { expression: "for the first time", meaning: "처음으로" },
  { expression: "to tell the truth", meaning: "사실대로 말하자면" },
  { expression: "not only A but (also) B = B as well as A", meaning: "A뿐만 아니라 B도 역시" },
  { expression: "depend on(upon)", meaning: "~에 의지(의존)하다, ~에 달려있다, 믿다" },
  { expression: "forget to 동사", meaning: "(미래에) ~할것을 잊어버리다" },
  { expression: "give one's love to 명사", meaning: "~에게 안부를 전해주다" },
  { expression: "ought to 동사", meaning: "~해야 한다" },
  { expression: "take up", meaning: "(공간,,시간을) 차지하다, 착수(시작)하다" },
  { expression: "be busy (in) 동사~ing", meaning: "~하느라 바쁘다" },
  { expression: "by oneself", meaning: "혼자서, 혼자 힘으로" },
  { expression: "far away", meaning: "멀리 (떨어져 있는)" },
  { expression: "with a smile", meaning: "미소를 지으며" },
  { expression: "both A and B", meaning: "A와 B 둘 다" },
  { expression: "believe in", meaning: "~의 존재를 믿다, 좋다고 믿다" },
  { expression: "come out", meaning: "나오다" },
  { expression: "cut down", meaning: "(나무를) 베어 넘어뜨리다" },
  { expression: "invite A to B(명사/동사)", meaning: "A를 B(명사)에 초대하다/A에게 B(동사)하도록 청하다" },
  { expression: "spend 돈(시간) (on[in]) 명사(동사~ing)", meaning: "~에 돈을 쓰다(시간을 보내다)" },
  { expression: "be absent from", meaning: "~에 결석하다" },
  { expression: "each of", meaning: "각각, 각자" },
  { expression: "side by side", meaning: "나란히" },
  { expression: "up and down", meaning: "위아래로(오르내리며), 이리저리(왔다갔다)" },
  { expression: "either A or B", meaning: "A 또는 B" },
  { expression: "neither A nor B", meaning: "A도 B도 아닌" },
  { expression: "clean up(out)", meaning: "청소하다" },
  { expression: "hurry up", meaning: "서두르다" },
  { expression: "make sure", meaning: "확인하다, 확실히 ~하다" },
  { expression: "put up", meaning: "올리다(세우다), 내붙이다" },
  { expression: "run across", meaning: "뛰어 건너다, 우연히 만나다" },
  { expression: "be divided into", meaning: "~로 나누어져 있다" },
  { expression: "at least", meaning: "적어도" },
  { expression: "at the same time", meaning: "동시에" },
  { expression: "instead of", meaning: "~대신에" },
  { expression: "not A but B", meaning: "A가 아니라 B" },
  { expression: "hold on", meaning: "(전화를 끊지 않고) 잠시 기다리다" },
  { expression: "make money", meaning: "돈을 벌다" },
  { expression: "make up", meaning: "구성하다, 만들어내다, (이야기를) 지어내다, 화장하다" },
  { expression: "run after", meaning: "뒤쫓다" },
  { expression: "wash(do) the dishes", meaning: "설거지하다" },
  { expression: "be filled with", meaning: "~로 가득 차다" },
  { expression: "a pair of", meaning: "(같은것 2개로 된) 한 쌍(켤레)의" },
  { expression: "again and again", meaning: "몇 번이고, 되풀이해서" },
  { expression: "from now on", meaning: "지금부터 계속" },
  { expression: "not ~ at all", meaning: "전혀 ~아니다" },
  { expression: "call out", meaning: "큰 소리로 부르다(외치다)" },
  { expression: "care about", meaning: "걱정(염려)하다, ~에 마음(신경)쓰다" },
  { expression: "laugh at", meaning: "비웃다, 보고(듣고) 웃다" },
  { expression: "make a plan", meaning: "계획을 세우다" },
  { expression: "pass by", meaning: "지나가다, (시간이) 지나다" },
  { expression: "be worth 동사~ing", meaning: "~할 가치가 있다" },
  { expression: "a couple of", meaning: "둘의, 두셋의" },
  { expression: "a kind of", meaning: "일종의" },
  { expression: "at(in) the end of", meaning: "~의 끝에" },
  { expression: "not ~ any longer(more) = no longer(more)", meaning: "더 이상 ~않다" },
  { expression: "agree with", meaning: "~에(게) 동의하다, ~와 (의견이) 일치하다, ~에 맞다" },
  { expression: "cry out", meaning: "큰 소리로 외치다" },
  { expression: "do a good job", meaning: "일을 잘 해내다" },
  { expression: "enjoy oneself", meaning: "즐겁게 지내다" },
  { expression: "make up one's mind", meaning: "결심(결정)하다" },
  { expression: "be curious about", meaning: "~에 호기심이 있다, 알고 싶어하다" },
  { expression: "a long time ago", meaning: "오래전에, 옛날에" },
  { expression: "all the way", meaning: "내내(줄곧)" },
  { expression: "in the middle of", meaning: "~의 한가운데(도중)에" },
  { expression: "not always/every(all) ~ not", meaning: "언제나/모든 것이 ~인 것은 아니다(부분 부정)" },
  { expression: "have(get) a chance to 동사", meaning: "~할 기회를 갖다" },
  { expression: "plan to 동사", meaning: "~할 계획이다" },
  { expression: "take it easy", meaning: "서두르자않고 느긋하게 하다, 화내지 않다, (작별인사로) 안녕" },
  { expression: "turn around", meaning: "회전하다, 뒤돌아보다" },
  { expression: "work for", meaning: "~을 위해 일하다, ~에 근무하다" },
  { expression: "be known to 명사", meaning: "~에 알려져 있다" },
  { expression: "in a hurry", meaning: "서둘러, 급히" },
  { expression: "in the past", meaning: "과거에는" },
  { expression: "one another", meaning: "서로" },
  { expression: "사역동사+목적어+동사(원형부정사)", meaning: "~에게 ~를 시키다(하게 하다)" },
  { expression: "finish 동사~ing", meaning: "~하는 것을 끝마치다" },
  { expression: "go to sleep", meaning: "잠들다" },
  { expression: "have a headache", meaning: "머리가 아프다" },
  { expression: "leave for", meaning: "~을 향해 떠나다(출발하다)" },
  { expression: "mind 동사~ing", meaning: "~하는 것을 꺼리다" },
  { expression: "be sure of(that)", meaning: "확신하다" },
  { expression: "after all", meaning: "결국, 어찌되었건" },
  { expression: "in time", meaning: "때를 맞춰, 늦지 않게" },
  { expression: "most of all", meaning: "무엇보다도" },
  { expression: "have(get)+목적어+과거분사", meaning: "~가 ~되게 하다, ~를 ~당하다" },
  { expression: "bring about", meaning: "일으키다, 생기게 하다" },
  { expression: "give a big hand", meaning: "박수갈채를 보내다" },
  { expression: "have no idea", meaning: "전혀 모르다" },
  { expression: "point to 명사", meaning: "가리키다" },
  { expression: "turn A (in)to B", meaning: "A를 B로 바꾸다" },
  { expression: "be made up of", meaning: "~로 이루어지다(구성되다)" },
  { expression: "a group of", meaning: "한 무리의, 한 떼의" },
  { expression: "far from", meaning: "~로부터 먼(멀리), 결코 ~이 아닌" },
  { expression: "in trouble", meaning: "곤경에 빠진" },
  { expression: "So(Neither)+(조)동사+주어", meaning: "~도 또한 그렇다(그렇지 않다)" },
  { expression: "get back", meaning: "돌아오다(가다), 되돌려 받다" },
  { expression: "look into", meaning: "들여다보다, 조사하다" },
  { expression: "move to(into)", meaning: "~로 이사(이동)하다" },
  { expression: "stand in line", meaning: "줄을 서다" },
  { expression: "turn right/left", meaning: "우/좌회전을 하다" },
  { expression: "be over", meaning: "끝나다" },
  { expression: "as a result", meaning: "결과적으로" },
  { expression: "for sale", meaning: "팔려고 내놓은, 판매용인" },
  { expression: "in many/some ways", meaning: "여러/몇 가지 면에서" },
  { expression: "so 형용사/부사 (that)", meaning: "너무 ~해서 ~하다(결과)" },
  { expression: "fall down", meaning: "넘어지다, 무너지다, 떨어지다" },
  { expression: "fall in love (with)", meaning: "(~와) 사랑에 빠지다" },
  { expression: "sound like", meaning: "~처럼 들리다, ~인것 같다" },
  { expression: "take(make) a trip (to 명사)", meaning: "(~을) 여행하다" },
  { expression: "watch out", meaning: "조심(주의)하다" },
  { expression: "be made from", meaning: "~로 만들어지다" },
  { expression: "as you know", meaning: "너(여러분)도 알다시피" },
  { expression: "here and there", meaning: "여기저기에" },
  { expression: "on foot", meaning: "걸어서" },
  { expression: "so that", meaning: "~하기 위하여, ~하도록(목적)" },
  { expression: "get married (to 사람)", meaning: "(~와) 결혼하다" },
  { expression: "go on a picnic", meaning: "소풍을 가다" },
  { expression: "look out", meaning: "밖을 내다보다, 조심하다" },
  { expression: "put off (동사~ing)", meaning: "미루다, 연기하다" },
  { expression: "take(get, have) a rest", meaning: "쉬다, 휴식을 취하다" },
  { expression: "be popular with [among]", meaning: "~에게 인기가 좋다" },
  { expression: "above all", meaning: "무엇보다도, 특히" },
  { expression: "for a moment", meaning: "잠시 동안" },
  { expression: "once upon a time", meaning: "옛날에" },
  { expression: "as 형용사/부사 as possible[one can]", meaning: "가능한 한 ~한/하게" },
  { expression: "eat out", meaning: "외식하다" },
  { expression: "give one's best wishes to 명사", meaning: "~에게 안부를 전하다" },
  { expression: "line up", meaning: "줄을 서다" },
  { expression: "look after", meaning: "돌보다" },
  { expression: "take a shower/bath", meaning: "샤워/목욕하다" },
  { expression: "be sold out", meaning: "다 팔리다, 매진되다" },
  { expression: "(just) around the corner", meaning: "길모퉁이를 돌아선 곳에, 바로 가까이에, 바로 다가와 있는" },
  { expression: "before long", meaning: "머지않아, 곧" },
  { expression: "for sure", meaning: "틀림없이, 확실히" },
  { expression: "as 형용사/부사 as ~", meaning: "~만큼 ~한" },
  { expression: "not as[so] 형용사/부사 as ~", meaning: "~만큼 ~하지 않은" },
  { expression: "advise A to 동사", meaning: "A에게 ~하도록 충고하다" },
  { expression: "do A a favor", meaning: "A의 부탁을 들어주다, A에게 호의를 베풀다" },
  { expression: "fill A with B", meaning: "A를 B로 채우다" },
  { expression: "keep ~ in mind", meaning: "명심하다, 염두에 두다" },
  { expression: "take place", meaning: "(사건 등이) 일어나다, (행사 등이) 열리다" },
  { expression: "be[get] angry with[at, about]", meaning: "~에게[에 대해] 화를 내다" },
  { expression: "at a time", meaning: "한 번에" },
  { expression: "on the phone", meaning: "전화상으로, 통화 중인" },
  { expression: "sooner or later", meaning: "조만간" },
  { expression: "배수사+as 형용사/부사 as ~ =배수사+비교급+than ~", meaning: "~의 몇 배" },
  { expression: "fall on", meaning: "(특별한 날이) 바로 ~날이다" },
  { expression: "get off", meaning: "(탈것에서) 내리다" },
  { expression: "give out", meaning: "공개[발표]하다, (소리,빛 등을) 내다, 나눠주다" },
  { expression: "have trouble[difficulty]", meaning: "어려움을 겪다" },
  { expression: "stand for", meaning: "나타내다, 상징하다, 지지하다" },
  { expression: "be similar to 명사", meaning: "~와 비슷하다" },
  { expression: "after a while", meaning: "잠시 후에, 곧" },
  { expression: "none of", meaning: "아무(것)도 ~않다" },
  { expression: "so far", meaning: "지금까지, 여기까지" },
  { expression: "(much, a lot, even, far, still+) 비교급+than", meaning: "~보다 (훨씬) 더 ~한" },
  { expression: "come along", meaning: "함께 가다, 동행하다" },
  { expression: "get better", meaning: "더 좋아지다, (병 등이) 회복되다" },
  { expression: "go around", meaning: "~ 둘레를 돌다" },
  { expression: "keep[get] in touch (with)", meaning: "(~와) 계속 연락하고 지내다" },
  { expression: "warm up", meaning: "준비 운동을 하다, 따뜻하게 하다" },
  { expression: "be satisfied with", meaning: "~에 만족하다" },
  { expression: "a little bit", meaning: "조금" },
  { expression: "many times", meaning: "여러 번" },
  { expression: "only a few[little]", meaning: "불과 얼마 안 되는, 극소수[극소량]의" },
  { expression: "The 비교급 ~, the 비교급 ~", meaning: "~하면 할수록 더 ~하다" },
  { expression: "do an experiment", meaning: "실험하다" },
  { expression: "get[be] lost", meaning: "길을 잃다" },
  { expression: "have a lot to do with", meaning: "~와 많은 관계가 있다" },
  { expression: "send out", meaning: "내보내다, 발송하다" },
  { expression: "take an[one's] order", meaning: "주문을 받다" },
  { expression: "be surprised at", meaning: "~에 놀라다" },
  { expression: "a cup/glass of", meaning: "한 컵/잔의" },
  { expression: "according to 명사", meaning: "~에 따르면, ~에 따라서" },
  { expression: "for some time", meaning: "한동안" },
  { expression: "비교급 and 비교급", meaning: "점점 더 ~한" },
  { expression: "cut out", meaning: "잘라내다, 오려내다" },
  { expression: "get[do, take] exercise", meaning: "운동을 하다" },
  { expression: "get out of", meaning: "~에서 나오[가]다, ~에서 내리다" },
  { expression: "do for a walk/drive/jog", meaning: "산책/드라이브/조깅하러 가다" },
  { expression: "run around", meaning: "뛰어 돌아다니다" },
  { expression: "be mean to 명사(사람)", meaning: "~에게 심술궂게 굴다" },
  { expression: "a great deal of", meaning: "(양이) 많은, 다량의" },
  { expression: "ahead of", meaning: "~보다 앞에[앞서서]" },
  { expression: "from time to time", meaning: "때때로, 가끔" },
  { expression: "비교급+than any other+단수명사=부정 주어+비교급+than=the 최상급", meaning: "가장 ~한" },
  { expression: "are for", meaning: "돌보다, 좋아하다" },
  { expression: "give away", meaning: "거저 주다" },
  { expression: "do out of", meaning: "~에서 밖으로 나가다" },
  { expression: "have a talk (with)", meaning: "(~와) 이야기를 나누다" },
  { expression: "run out of", meaning: "~이 바닥나다, 다 써버리다" },
  { expression: "be short of", meaning: "~가 부족하다" },
  { expression: "for a minute", meaning: "잠시 동안" },
  { expression: "in the end", meaning: "끝내, 마침내" },
  { expression: "in those days", meaning: "그 당시에는, 그 때는" },
  { expression: "What a[an] 형용사+명사 (주어+동사)!/How 형용사[부사] (주어+동사)!", meaning: "정말 ~구나!(감탄문)" },
  { expression: "add A to B(명사)", meaning: "B에 A를 더하다[첨가하다]" },
  { expression: "cannot[can't] help 동사~ing", meaning: "~하지 않을 수 없다" },
  { expression: "change A into B", meaning: "A를 B로 바꾸다" },
  { expression: "share A with B", meaning: "A를 B와 나누다[함께 하다]" },
  { expression: "try 동사~ing", meaning: "(시험삼아) ~해보다, 시도하다" },
  { expression: "be based on", meaning: "~에 바탕을 두다, ~에 근거하다" },
  { expression: "on and on", meaning: "계속해서" },
  { expression: "on sale", meaning: "할인 판매 중인, 판매 중인" },
  { expression: "the other day", meaning: "일전에, 며칠 전, (=a few days ago)" },
  { expression: "명령문,, and/or", meaning: "~해라,, 그러면/그렇지 않으면 ~" },
  { expression: "consist of", meaning: "~로 이루어지다, ~로 구성되다" },
  { expression: "drop by", meaning: "들르다" },
  { expression: "make fun of", meaning: "놀리다" },
  { expression: "shake hands (with)", meaning: "(~와) 악수하다" },
  { expression: "take pride in", meaning: "자랑스러워하다" },
  { expression: "be crowded with", meaning: "~로 붐비다" },
  { expression: "every time", meaning: "~할 때마다, 언제나[매번]" },
  { expression: "in danger", meaning: "위험에 빠진" },
  { expression: "in silence", meaning: "조용히, 말없이" },
  { expression: "as soon as", meaning: "~하자마자" },
  { expression: "sk A a favor", meaning: "A에게 부탁하다" },
  { expression: "get in", meaning: "(승용차처럼 작은 것을) 타다" },
  { expression: "give a hand", meaning: "도움을 주다" },
  { expression: "protect A from [against] B", meaning: "A를 B로부터 지키다[보호하다]" },
  { expression: "take ~ apart", meaning: "(기계 등을) 분해하다" },
  { expression: "be made into", meaning: "~가 되다" },
  { expression: "at the top of", meaning: "~의 맨 위에, ~의 일등인" },
  { expression: "for instance", meaning: "예를 들면" },
  { expression: "in addition", meaning: "게다가" },
  { expression: "even if[though]", meaning: "비록 ~일지라도" },
  { expression: "break out", meaning: "(전쟁,,화재,,질병이) 갑자기 일어나다" },
  { expression: "die from", meaning: "(부상,,부주의 등으로) 죽다" },
  { expression: "feel like 동사~ing[명사]", meaning: "~하고 싶다, ~라는 느낌이 들다, ~인[일] 것 같다" },
  { expression: "hang up", meaning: "전화를 끊다, 걸어두다" },
  { expression: "look up", meaning: "찾아보다, 올려다보다" },
  { expression: "be open to 명사", meaning: "~에 개방되어 있다, ~이 이용할 수 있다" },
  { expression: "in public", meaning: "공개적으로, 사람들 앞에서" },
  { expression: "in the shape of", meaning: "~의 모양으로" },
  { expression: "one by one", meaning: "한 명씩[하나씩]" },
  { expression: "If 과거동사, 과거조동사+동사원형", meaning: "~한다면[이라면] ~할텐데[일텐데](현재,,미래 사실 반대 가정)" },
  { expression: "look through", meaning: "훑어보다, 통해 보다" },
  { expression: "make an effort", meaning: "노력하다" },
  { expression: "make (good) use of", meaning: "(잘) 이용하다" },
  { expression: "see a doctor", meaning: "진찰을 받다" },
  { expression: "turn into", meaning: "~로 변하다, ~이 되다" },
  { expression: "be[get] used to 명사[동사~ing]", meaning: "~에 익숙해지다" },
  { expression: "all one's life", meaning: "평생" },
  { expression: "in the distance", meaning: "먼 곳에, 저 멀리" },
  { expression: "with joy/excitement", meaning: "기뻐서/흥분해서" },
  { expression: "If had 과거분사,과거조동사+have 과거분사", meaning: "~했더라면[였더라면] ~했을텐데[였을텐데] (과거 사실 반대 가정)" },
  { expression: "focus on", meaning: "~에 초점을 맞추다, ~에 집중하다" },
  { expression: "make a reservation", meaning: "예약하다" },
  { expression: "make oneself at home", meaning: "편안히 하다" },
  { expression: "set the table", meaning: "식탁을 차리다" },
  { expression: "turn over", meaning: "뒤집다, 넘기다" },
  { expression: "be familiar to 명사", meaning: "~에 잘 알려지다, ~에 눈[귀]이 익다" },
  { expression: "at noon/midnight", meaning: "정오/자정에" },
  { expression: "at the beginning of", meaning: "~의 초기[처음]에" },
  { expression: "or so", meaning: "(수량 뒤에서) ~쯤, 정도" },
  { expression: "as if[though]+과거동사", meaning: "마치 ~인 것처럼(현재 사실 반대 가정)" },
  { expression: "get rid of", meaning: "없애다, 제거하다" },
  { expression: "go abroad", meaning: "외국[해외]에 가다" },
  { expression: "make a call", meaning: "전화하다" },
  { expression: "pass away", meaning: "돌아가시다, 죽다" },
  { expression: "succeed in", meaning: "~에 성공하다" },
  { expression: "be anxious about", meaning: "~에 대해 걱정[염려]하다" },
  { expression: "as far as", meaning: "~까지, ~하는 한" },
  { expression: "in half", meaning: "절반으로" },
  { expression: "little by little", meaning: "조금씩, 점차로" },
  { expression: "I wish+과거동사", meaning: "~한다면 좋을텐데(현재 사실 반대 가정)" },
  { expression: "get[catch, attract] one's attention", meaning: "~의 관심을 끌다" },
  { expression: "fight for/against", meaning: "~을 위해/~에 대항해 싸우다" },
  { expression: "get well", meaning: "(병이) 낫다, 회복하다" },
  { expression: "have[get, take] a seat", meaning: "자리에 앉다" },
  { expression: "hit (up)on", meaning: "생각해내다" },
  { expression: "be sick in bed", meaning: "아파서 누워 있다" },
  { expression: "as usual", meaning: "여느 때처럼, 평소와 같이" },
  { expression: "on earth", meaning: "(의문문에서) 도대체, (부정문에서) 전혀, 이 세상의" },
  { expression: "upside down", meaning: "거꾸로, (위가 아래로 되게) 뒤집혀" },
  { expression: "How much/many/old/long/tall/high/fast/far/large/often/soon/many times?", meaning: "얼마나 많은(양)/많은(수)/나이 든/오래[긴]/키 큰/높이/빨리/멀리/큰/자주/일찍/여러 번?" },
  { expression: "cut down on", meaning: "(수량을) 줄이다" },
  { expression: "go wrong", meaning: "(일이) 잘 안 되다, 고장나다, 길을 잘못 들다" },
  { expression: "prefer A(명사) to B(명사)", meaning: "B보다 A를 더 좋아하다" },
  { expression: "see ~ off", meaning: "배웅[전송]하다" },
  { expression: "take[have] a look at", meaning: "보다" },
  { expression: "be dressed in", meaning: "입고 있다" },
  { expression: "day and night", meaning: "밤낮으로, 항상" },
  { expression: "first of all", meaning: "무엇보다도, 제일 먼저" },
  { expression: "over and over (again)", meaning: "여러 번, 반복해서" },
  { expression: "What time/day/kind/size?", meaning: "몇 시/무슨 요일/어떤 종류/무슨 치수?" },
  { expression: "ask for", meaning: "요구[요청]하다" },
  { expression: "die of", meaning: "(병,, 노령 등으로) 죽다" },
  { expression: "fail to 동사", meaning: "~하지 못하다" },
  { expression: "pay attention to 명사", meaning: "~에 주의를 기울이다" },
  { expression: "put out", meaning: "(불을) 끄다" },
  { expression: "be known as", meaning: "~로서 알려지다" },
  { expression: "at the age of", meaning: "~살 때에" },
  { expression: "on business", meaning: "사업상, 볼일이 있어" },
  { expression: "out of sight", meaning: "안 보이는 (곳에)" },
  { expression: "what+주어+동사", meaning: "~것, 무엇 ~인지(명사절: 주어, 보어,,목적어 기능)" },
  { expression: "come up", meaning: "다가오다, (떠)오르다, 싹트다" },
  { expression: "fall asleep", meaning: "잠들다" },
  { expression: "get out", meaning: "나가다" },
  { expression: "make up for", meaning: "벌충[보충]하다" },
  { expression: "put together", meaning: "모으다, 합치다" },
  { expression: "slow down", meaning: "(속도를) 늦추다" },
  { expression: "be free to 동사", meaning: "마음대로[자유롭게] ~하다" },
  { expression: "at the bottom of", meaning: "~의 아래쪽[밑바닥]에" },
  { expression: "or something", meaning: "~이나 뭔가" },
  { expression: "의문사(who/which/where/when/why/how)+주어+동사", meaning: "~인지(명사절: 주어, 보어, 목적어 기능)" },
  { expression: "check in", meaning: "(호텔,,공항에서) 투숙[탑승] 수속을 하다" },
  { expression: "live on", meaning: "(주식으로) 먹고 살다" },
  { expression: "pull out", meaning: "꺼내다, 뽑다" },
  { expression: "show up", meaning: "나타나다" },
  { expression: "take notes[a note] (of)", meaning: "적어두다, 노트하다" },
  { expression: "be ashamed of", meaning: "부끄러워하다" },
  { expression: "as well", meaning: "~도 또한, 게다가" },
  { expression: "day after day", meaning: "날마다, 매일매일" },
  { expression: "from place to place", meaning: "이리저리로, 여기저기로" },
  { expression: "whether ~ (or not)", meaning: "~인지 (아닌지)(명사절), ~이든지 (아니든지)(부사절)" },
  { expression: "have a runny nose", meaning: "콧물이 나다" },
  { expression: "put up with", meaning: "참다" },
  { expression: "set ~ free", meaning: "풀어주다, 자유롭게 하다" },
  { expression: "step on (one's foot)", meaning: "(누구의 발을) 밟다" },
  { expression: "surt the Internet", meaning: "인터넷을 서핑하다" },
  { expression: "be harmful to 명사", meaning: "~에 해롭다" },
  { expression: "for oneself", meaning: "혼자 힘으로, 스스로, 자신을 위해" },
  { expression: "on the other hand", meaning: "한편, 반면에" },
  { expression: "(With) best wishes", meaning: "행운[성공]을 빌며" },
  { expression: "if+주어+동사", meaning: "~인지(명사절), 만약 ~한다면(조건 부사절)" },
  { expression: "come to 동사/명사", meaning: "~하게 되다/~에 이르다, ~이 되다" },
  { expression: "gain[put on]/lose weight", meaning: "체중이 늘다/줄다" },
  { expression: "make a fire", meaning: "불을 피우다" },
  { expression: "make a speech", meaning: "연설을 하다" },
  { expression: "pay back", meaning: "(돈을) 갚다, 보복하다" },
  { expression: "be likely to 동사", meaning: "~할 것 같다" },
  { expression: "a sheet of", meaning: "한 장의 ~" },
  { expression: "on fire", meaning: "불이 나서, 불타서" },
  { expression: "on the other side (of)", meaning: "(~의) 반대쪽[맞은편]에, (~의) 다른 곳에" },
  { expression: "that+주어+동사", meaning: "~것(명사절:주어,,보어,,목적어,,동격 기능)" },
  { expression: "cut off", meaning: "잘라내다, 끊다" },
  { expression: "fill out", meaning: "(서류에) 써넣다, 기입하다" },
  { expression: "give off", meaning: "(냄새,, 빛 등을) 내뿜다, 방출하다" },
  { expression: "prepare for", meaning: "준비[대비]하다" },
  { expression: "tumble down", meaning: "굴러 떨어지다" },
  { expression: "be dying to 동사", meaning: "~하고 싶어 죽겠다" },
  { expression: "all night (long)", meaning: "밤새도록" },
  { expression: "along with", meaning: "~와 함께, ~에 더하여" },
  { expression: "in case of", meaning: "~의 경우에" },
  { expression: "It be+강조할 대상(주어,,목적어,,부사어)+that ~", meaning: "~한 것은 바로 ~이다(강조 구문)" },
  { expression: "come to an end", meaning: "끝나다, 마치다" },
  { expression: "hold out", meaning: "내밀다" },
  { expression: "long for[to 동사]", meaning: "간절히 바라다, 열망하다" },
  { expression: "set out", meaning: "출발하다, 시작하다, (음식 등을) 차려놓다" },
  { expression: "stay up", meaning: "자지 않고 일어나 있다" },
  { expression: "be responsible for", meaning: "~에 책임이 있다, ~의 원인이 되다" },
  { expression: "in advance", meaning: "미리" },
  { expression: "step by step", meaning: "한 걸음씩, 차근차근" },
  { expression: "with a sigh", meaning: "한숨을 쉬며" },
  { expression: "It takes (A) 시간 to 동사", meaning: "(A가) ~하는데 시간이 걸리다" },
  { expression: "break down", meaning: "고장이 나다" },
  { expression: "bring up", meaning: "기르다, 양육하다" },
  { expression: "give in", meaning: "굴복하다, 제출하다" },
  { expression: "go across", meaning: "건너가다, 가로질러 가다" },
  { expression: "look up to 명사", meaning: "존경하다, 우러러보다" },
  { expression: "be sick of", meaning: "~에 싫증나다, ~에 질리다" },
  { expression: "all of a sudden", meaning: "갑자기" },
  { expression: "in a second[minute]", meaning: "곧, 순식간에" },
  { expression: "in[with] surprise", meaning: "놀라서" },
  { expression: "관계대명사(who.which.that)+주어+동사", meaning: "~인[하는](형용사절)" },
  { expression: "begin with", meaning: "~부터[로] 시작하다" },
  { expression: "come up with", meaning: "생각해내다" },
  { expression: "keep out", meaning: "안에 들이지 않다, 들어가지 않다" },
  { expression: "lose/gain one's sight", meaning: "시력을 잃다/회복하다" },
  { expression: "pass out", meaning: "기절하다, 건네주다" },
  { expression: "take an exam", meaning: "시험을 보다" },
  { expression: "be anxious for[to 동사]", meaning: "매우 ~하고 싶어하다, 열망하다" },
  { expression: "in a row", meaning: "한 줄로, 연달아" },
  { expression: "one after another", meaning: "(셋 이상이) 차례로, 잇달아" },
  { expression: "관계부사(when.where.why.how)+주어+동사", meaning: "~인[하는](형용사절)" },
  { expression: "check out", meaning: "(책 등을) 체크하고 빌리다, (호텔,, 슈퍼에서) 계산하고 나오다, 확인[점검]하다" },
  { expression: "complain about[of]", meaning: "~에 대해 불평하다, 호소하다" },
  { expression: "dig up", meaning: "파내다, 캐내다" },
  { expression: "fall off", meaning: "떨어지다" },
  { expression: "keep a[one's] promise", meaning: "약속을 지키다" },
  { expression: "be friendly with", meaning: "~와 사이가 좋다" },
  { expression: "due to 명사", meaning: "~때문에" },
  { expression: "in the center of", meaning: "~의 중심에" },
  { expression: "plenty of", meaning: "많은, 다수[량]의" },
  { expression: "one ~ the other", meaning: "(둘 중의) 하나 ~ 나머지 하나" },
  { expression: "die out", meaning: "죽어 없어지다, 소멸하다" },
  { expression: "fill up", meaning: "가득 채우다[차다]" },
  { expression: "hold up", meaning: "들어 올리다, 떠받치다" },
  { expression: "promise to 동사", meaning: "~하기로 약속하다" },
  { expression: "run into", meaning: "우연히 만나다, ~와 충돌하다" },
  { expression: "be rich in", meaning: "~이 많이 있다, ~이 풍부하다" },
  { expression: "at work", meaning: "일터에서, 일하고 있는" },
  { expression: "by express", meaning: "속달[급행]로" },
  { expression: "to one's surprise", meaning: "놀랍게도" },
  { expression: "the same as", meaning: "~와 같은" },
  { expression: "call on", meaning: "방문하다" },
  { expression: "give it a try", meaning: "시도하다" },
  { expression: "have ~ in common", meaning: "공통으로 ~을 갖고 있다" },
  { expression: "know ~ by heart", meaning: "외우고 있다" },
  { expression: "mean to 동사", meaning: "작정하다, 의도하다" },
  { expression: "turn away", meaning: "딴 데로 돌리다, 외면하다" },
  { expression: "be thankful for", meaning: "~에 대해 감사히 여기다" },
  { expression: "at the sight of", meaning: "~을 보자[보고]" },
  { expression: "in general", meaning: "일반적으로" },
  { expression: "in harmony with", meaning: "~와 조화를 이루어" },
  { expression: "can afford to 동사", meaning: "~할 여유가 있다" },
  { expression: "make a[one's] choice", meaning: "선택하다" },
  { expression: "pick out", meaning: "골라내다, 식별하다" },
  { expression: "play a role", meaning: "역할을 하다" },
  { expression: "provide A with B", meaning: "A(사람,,사물)에게 B(사물)를 공급[제공]하다" },
  { expression: "be located in[at]", meaning: "~에 있다, 위치하다" },
  { expression: "in reality", meaning: "실제는, 사실상" },
  { expression: "in search of", meaning: "~을 찾아서" },
  { expression: "no wonder", meaning: "~은 당연하다, 놀랄 것도 없다" },
  { expression: "up to 명사", meaning: "~까지, ~에 달려 있는" },
  { expression: "cut in line", meaning: "새치기하다" },
  { expression: "devote oneself to 명사", meaning: "~에 몰두[전념]하다, ~에 헌신하다" },
  { expression: "keep A from B(동사~ing)", meaning: "A가 B하는 것을 막다[못하게 하다]" },
  { expression: "leave out", meaning: "빼다" },
  { expression: "run for", meaning: "~에 입후보하다" },
  { expression: "suffer from", meaning: "~로 고통을 겪다, 앓다" },
  { expression: "be eager for[to 동사]", meaning: "간절히 ~하고 싶어하다, 열망하다" },
  { expression: "by mistake", meaning: "실수로" },
  { expression: "by way of", meaning: "~로써(수단,,방법), ~을 지나서[경유하여]" },
  { expression: "out of breath", meaning: "숨이 차서" },
  { expression: "call up", meaning: "전화하다" },
  { expression: "calm down", meaning: "진정시키다, 진정하다" },
  { expression: "go through", meaning: "겪다" },
  { expression: "have a sore throat", meaning: "목이 아프다" },
  { expression: "remind A of B", meaning: "A에게 B를 떠올리게[생각나게] 하다" },
  { expression: "stop A from B(동사~ing)", meaning: "A가 B하는 것을 막다[못하게 하다]" },
  { expression: "be impressed by[with]", meaning: "~에 감동받다" },
  { expression: "by the time (that)", meaning: "~할 즈음, ~할 때까지" },
  { expression: "in sight", meaning: "보이는 (곳에)" },
  { expression: "that is (to say)", meaning: "즉" },
  { expression: "burst into", meaning: "갑자기 ~하다, 불쑥 뛰어들다" },
  { expression: "divide A into B", meaning: "A를 B로 나누다" },
  { expression: "head for", meaning: "~로 향하다[향해 나아가다]" },
  { expression: "keep away from", meaning: "~로부터 멀리하다, ~에 가까이 못하게 하다" },
  { expression: "put away", meaning: "치우다" },
  { expression: "regard A as B", meaning: "A를 B로 여기다[간주하다, 생각하다]" },
  { expression: "be content with", meaning: "~에 만족하다" },
  { expression: "all at once", meaning: "갑자기, 모두 동시에[한꺼번에]" },
  { expression: "except for", meaning: "~을 제외하고" },
  { expression: "in vain", meaning: "헛되이, 보람 없이" },
  { expression: "cause A to B(동사)", meaning: "A가 B하게 하다" },
  { expression: "contribute to 명사", meaning: "~에 기여하다" },
  { expression: "fail in", meaning: "~에 실패하다" },
  { expression: "have a cough", meaning: "기침하다" },
  { expression: "stare at", meaning: "빤히 보다, 응시하다" },
  { expression: "turn out", meaning: "~로 판명되다, (전등,,수도 등을) 끄다[잠그다]" },
  { expression: "be concerned with", meaning: "~와 관계가 있다, ~에 관계하다" },
  { expression: "hand in hand", meaning: "손을 맞잡고" },
  { expression: "in secret", meaning: "비밀로, 남몰래" },
  { expression: "what is more", meaning: "더욱이, 게다가" },
  { expression: "carry out", meaning: "실행하다, 성취하다" },
  { expression: "catch up with", meaning: "따라잡다" },
  { expression: "keep up", meaning: "계속 유지하다" },
  { expression: "prefer to A(동사) (rather than B(동사))", meaning: "(B하기보다) A하기를 더 좋아하다" },
  { expression: "pull up", meaning: "(차를) 멈추다, 잡아 올리다" },
  { expression: "work out", meaning: "(문제를) 풀다, (계획을) 세우다, 잘되어 가다, 운동하다" },
  { expression: "be bound for", meaning: "~행이다, ~로 향하다" },
  { expression: "by chance", meaning: "우연히, 뜻밖에" },
  { expression: "in contrast", meaning: "대조적으로" },
  { expression: "in favor of", meaning: "~에 찬성하여, ~을 위하여" },
  { expression: "breathe in", meaning: "숨을 들이쉬다" },
  { expression: "go too far", meaning: "정도가 지나치다" },
  { expression: "make out", meaning: "알아보다, 이해하다" },
  { expression: "fall behind", meaning: "뒤떨어지다, 뒤처지다" },
  { expression: "kill time", meaning: "(빈둥거리며) 시간을 보내다" },
  { expression: "place an order (for)", meaning: "주문을 하다" },
  { expression: "be fond of", meaning: "~을 좋아하다" },
  { expression: "at hand", meaning: "바로 가까이에, 즉시 쓸 수 있는" },
  { expression: "into pieces", meaning: "산산조각으로" },
  { expression: "of use", meaning: "쓸모 있는" },
  { expression: "cooperate with", meaning: "~와 협력하다" },
  { expression: "expect to 동사", meaning: "~하기를 기대하다" },
  { expression: "have respect for", meaning: "존경하다, 존중하다" },
  { expression: "leave ~ behind", meaning: "두고 오다[가다]" },
  { expression: "lie down", meaning: "눕다" },
  { expression: "make a (big) difference", meaning: "(큰) 차이를 낳다, (매우) 중요하다" },
  { expression: "be through (with)", meaning: "끝내다, 마치다" },
  { expression: "a slice of", meaning: "얇게 썬 한 조각의" },
  { expression: "for good", meaning: "영원히" },
  { expression: "in person", meaning: "본인이 직접, 몸소" },
  { expression: "come to one's mind", meaning: "(생각이) 마음에 떠오르다" },
  { expression: "dare to 동사", meaning: "감히[과감히] ~하다" },
  { expression: "pass through", meaning: "통과하다, 겪다" },
  { expression: "pay a visit to 명사", meaning: "방문하다" },
  { expression: "wish to 동사", meaning: "~하기를 바라다[소망하다]" },
  { expression: "be willing to 동사", meaning: "기꺼이 ~하다" },
  { expression: "for one thing", meaning: "우선, 첫째로" },
  { expression: "in need", meaning: "어려운 때, 곤경에 빠진" },
  { expression: "no way", meaning: "조금도 ~않다, (요구,제안에 대해) 싫다" },
  { expression: "what is called", meaning: "소위, 이른바" },
];